#if !defined HEADER_GUARD_TranslatorLimits
#    define  HEADER_GUARD_TranslatorLimits 1

#define TranslatorLimits_LenName_cnst 63
#define TranslatorLimits_LenString_cnst 255
#define TranslatorLimits_LenNumber_cnst 63
#define TranslatorLimits_BlankChars_cnst 1023
#define TranslatorLimits_ImportedModules_cnst 127
#define TranslatorLimits_GlobalConsts_cnst 2047
#define TranslatorLimits_GlobalTypes_cnst 127
#define TranslatorLimits_GlobalVars_cnst 255
#define TranslatorLimits_VarsSeparatedByComa_cnst 31
#define TranslatorLimits_GlobalProcedures_cnst 1023
#define TranslatorLimits_ModuleTextSize_cnst 262143
#define TranslatorLimits_MaxLexemsToModule_cnst 4095
#define TranslatorLimits_ArrayDimension_cnst 7
#define TranslatorLimits_VarsInRecord_cnst 255
#define TranslatorLimits_RecordExt_cnst 15
#define TranslatorLimits_Params_cnst 15
#define TranslatorLimits_Consts_cnst 255
#define TranslatorLimits_Vars_cnst 31
#define TranslatorLimits_Procedures_cnst 31
#define TranslatorLimits_DeepProcedures_cnst 7
#define TranslatorLimits_Statements_cnst 255
#define TranslatorLimits_DeepStatements_cnst 15
#define TranslatorLimits_IfBranches_cnst 255
#define TranslatorLimits_Selectors_cnst 63
#define TranslatorLimits_TermsInSum_cnst 255
#define TranslatorLimits_FactorsInTerm_cnst 255

#endif
