/* Generated by Vostok - Oberon-07 translator */

#define O7_BOOL_UNDEFINED
#include <o7.h>

#include "CliParser.h"

#define CliParser_Args_tag V_Base_tag
extern void CliParser_Args_undef(struct CliParser_Args *r) {
	V_Base_undef(&r->_);
	memset(&r->src, 0, sizeof(r->src));
	r->srcLen = O7_INT_UNDEF;
	memset(&r->cmd, 0, sizeof(r->cmd));
	r->script = O7_BOOL_UNDEF;
	memset(&r->outC, 0, sizeof(r->outC));
	memset(&r->resPath, 0, sizeof(r->resPath));
	memset(&r->tmp, 0, sizeof(r->tmp));
	r->resPathLen = O7_INT_UNDEF;
	r->srcNameEnd = O7_INT_UNDEF;
	memset(&r->modPath, 0, sizeof(r->modPath));
	memset(&r->cDirs, 0, sizeof(r->cDirs));
	memset(&r->cc, 0, sizeof(r->cc));
	r->modPathLen = O7_INT_UNDEF;
	r->sing = 0u;
	r->init = O7_INT_UNDEF;
	r->arg = O7_INT_UNDEF;
}

extern o7_bool CliParser_GetParam(int str_len0, o7_char str[/*len0*/], int *i, int *arg) {
	o7_bool ret;
	int j;

	j = (*i);
	ret = CLI_Get(str_len0, str, &(*i), (*arg));
	(*arg) = o7_add((*arg), 1);
	if (ret && Platform_Windows && (str[o7_ind(str_len0, j)] == (o7_char)'\'') && (o7_cmp((*arg), CLI_count) < 0)) {
		str[o7_ind(str_len0, j)] = (o7_char)' ';
		while ((o7_cmp((*arg), CLI_count) < 0) && ret && (str[o7_ind(str_len0, o7_sub((*i), 1))] != (o7_char)'\'')) {
			str[o7_ind(str_len0, (*i))] = (o7_char)' ';
			(*i) = o7_add((*i), 1);
			ret = CLI_Get(str_len0, str, &(*i), (*arg));
			(*arg) = o7_add((*arg), 1);
		}
		str[o7_ind(str_len0, o7_sub((*i), 1))] = 0x00u;
	}
	(*i) = o7_add(j, StringStore_TrimChars(str_len0, str, j));
	return ret;
}

static o7_bool IsEqualStr(int str_len0, o7_char str[/*len0*/], int ofs, int sample_len0, o7_char sample[/*len0*/]) {
	int i;

	i = 0;
	while ((str[o7_ind(str_len0, ofs)] == sample[o7_ind(sample_len0, i)]) && (sample[o7_ind(sample_len0, i)] != 0x00u) && (ofs < o7_sub(str_len0, 1)) && (ofs < o7_sub(sample_len0, 1))) {
		ofs = o7_add(ofs, 1);
		i = o7_add(i, 1);
	}
	return str[o7_ind(str_len0, ofs)] == sample[o7_ind(sample_len0, i)];
}

static int CopyPath(struct CliParser_Args *args, int *arg);
static o7_bool CopyPath_CopyInfrPart(int str_len0, o7_char str[/*len0*/], int *i, int *arg, int add_len0, o7_char add[/*len0*/]) {
	o7_bool ret;

	ret = CLI_Get(str_len0, str, &(*i), (*arg)) && StringStore_CopyCharsNull(str_len0, str, &(*i), add_len0, add);
	if (ret) {
		(*i) = o7_add((*i), 1);
		str[o7_ind(str_len0, (*i))] = 0x00u;
	}
	return ret;
}

static int CopyPath(struct CliParser_Args *args, int *arg) {
	int i, dirsOfs, ccLen, count, optLen, ret;
	o7_char opt[256];
	memset(&opt, 0, sizeof(opt));

	i = 0;
	dirsOfs = 0;
	(*args).cDirs[0] = 0x00u;
	(*args).tmp[0] = 0x00u;
	ccLen = 0;
	count = 0;
	(*args).sing = 0;
	ret = CliParser_ErrNo_cnst;
	optLen = 0;
	(*args).init =  - 1;
	while ((ret == CliParser_ErrNo_cnst) && (count < 32) && (o7_cmp((*arg), CLI_count) < 0) && CLI_Get(256, opt, &optLen, (*arg)) && !IsEqualStr(256, opt, 0, 2, (o7_char *)"--")) {
		optLen = 0;
		if ((o7_strcmp(256, opt, 2, (o7_char *)"-i") == 0) || (o7_strcmp(256, opt, 2, (o7_char *)"-m") == 0)) {
			(*arg) = o7_add((*arg), 1);
			if (o7_cmp((*arg), CLI_count) >= 0) {
				ret = CliParser_ErrNotEnoughArgs_cnst;
			} else if (CLI_Get(4096, (*args).modPath, &i, (*arg))) {
				if (o7_strcmp(256, opt, 2, (o7_char *)"-i") == 0) {
					(*args).sing |= 1u << count;
				}
				i = o7_add(i, 1);
				(*args).modPath[o7_ind(4096, i)] = 0x00u;
				count = o7_add(count, 1);
			} else {
				ret = CliParser_ErrTooLongModuleDirs_cnst;
			}
		} else if (o7_strcmp(256, opt, 2, (o7_char *)"-c") == 0) {
			(*arg) = o7_add((*arg), 1);
			if (o7_cmp((*arg), CLI_count) >= 0) {
				ret = CliParser_ErrNotEnoughArgs_cnst;
			} else if (CLI_Get(4096, (*args).cDirs, &dirsOfs, (*arg)) && (dirsOfs < O7_LEN((*args).cDirs) - 1)) {
				dirsOfs = o7_add(dirsOfs, 1);
				(*args).cDirs[o7_ind(4096, dirsOfs)] = 0x00u;
				Log_Str(8, (o7_char *)"cDirs = ");
				Log_StrLn(4096, (*args).cDirs);
			} else {
				ret = CliParser_ErrTooLongCDirs_cnst;
			}
		} else if (o7_strcmp(256, opt, 3, (o7_char *)"-cc") == 0) {
			(*arg) = o7_add((*arg), 1);
			if (o7_cmp((*arg), CLI_count) >= 0) {
				ret = CliParser_ErrNotEnoughArgs_cnst;
			} else if (CliParser_GetParam(4096, (*args).cc, &ccLen, &(*arg))) {
				(*arg) = o7_sub((*arg), 1);
			} else {
				ret = CliParser_ErrTooLongCc_cnst;
			}
		} else if (o7_strcmp(256, opt, 5, (o7_char *)"-infr") == 0) {
			(*arg) = o7_add((*arg), 1);
			if (o7_cmp((*arg), CLI_count) >= 0) {
				ret = CliParser_ErrNotEnoughArgs_cnst;
			} else if (Platform_Posix && CopyPath_CopyInfrPart(4096, (*args).modPath, &i, &(*arg), 23, (o7_char *)"/singularity/definition") && CopyPath_CopyInfrPart(4096, (*args).modPath, &i, &(*arg), 8, (o7_char *)"/library") && CopyPath_CopyInfrPart(4096, (*args).cDirs, &dirsOfs, &(*arg), 27, (o7_char *)"/singularity/implementation") || Platform_Windows && CopyPath_CopyInfrPart(4096, (*args).modPath, &i, &(*arg), 23, (o7_char *)"\\singularity\\definition") && CopyPath_CopyInfrPart(4096, (*args).modPath, &i, &(*arg), 8, (o7_char *)"\\library") && CopyPath_CopyInfrPart(4096, (*args).cDirs, &dirsOfs, &(*arg), 27, (o7_char *)"\\singularity\\implementation")) {
				(*args).sing |= 1u << count;
				count = o7_add(count, 2);
			} else {
				ret = CliParser_ErrTooLongModuleDirs_cnst;
			}
		} else if (o7_strcmp(256, opt, 5, (o7_char *)"-init") == 0) {
			(*arg) = o7_add((*arg), 1);
			if (o7_cmp((*arg), CLI_count) >= 0) {
				ret = CliParser_ErrNotEnoughArgs_cnst;
			} else if (!CLI_Get(256, opt, &optLen, (*arg))) {
				ret = CliParser_ErrUnknownInit_cnst;
			} else if (o7_strcmp(256, opt, 2, (o7_char *)"no") == 0) {
				(*args).init = GeneratorC_VarInitNo_cnst;
			} else if (o7_strcmp(256, opt, 5, (o7_char *)"undef") == 0) {
				(*args).init = GeneratorC_VarInitUndefined_cnst;
			} else if (o7_strcmp(256, opt, 4, (o7_char *)"zero") == 0) {
				(*args).init = GeneratorC_VarInitZero_cnst;
			} else {
				ret = CliParser_ErrUnknownInit_cnst;
			}
			optLen = 0;
		} else if (o7_strcmp(256, opt, 2, (o7_char *)"-t") == 0) {
			(*arg) = o7_add((*arg), 1);
			if (o7_cmp((*arg), CLI_count) >= 0) {
				ret = CliParser_ErrNotEnoughArgs_cnst;
			} else if (!CLI_Get(1024, (*args).tmp, &optLen, (*arg))) {
				ret = CliParser_ErrTooLongTemp_cnst;
			}
			optLen = 0;
		} else {
			ret = CliParser_ErrUnexpectArg_cnst;
		}
		(*arg) = o7_add((*arg), 1);
	}
	if (o7_add(i, 1) < O7_LEN((*args).modPath)) {
		(*args).modPathLen = o7_add(i, 1);
		(*args).modPath[o7_ind(4096, o7_add(i, 1))] = 0x00u;
		if (count >= 32) {
			ret = CliParser_ErrTooManyModuleDirs_cnst;
		}
	} else {
		ret = CliParser_ErrTooLongModuleDirs_cnst;
		(*args).modPath[O7_LEN((*args).modPath) - 1] = 0x00u;
		(*args).modPath[O7_LEN((*args).modPath) - 2] = 0x00u;
		(*args).modPath[O7_LEN((*args).modPath) - 3] = (o7_char)'#';
	}
	return ret;
}

static int ToC(struct CliParser_Args *args, int ret);
static int ToC_ParseCommand(int src_len0, o7_char src[/*len0*/], o7_bool *script);
static void ToC_ParseCommand_Empty(int src_len0, o7_char src[/*len0*/], int *j) {
	while ((src[o7_ind(src_len0, (*j))] == (o7_char)' ') || (src[o7_ind(src_len0, (*j))] == 0x09u)) {
		(*j) = o7_add((*j), 1);
	}
}

static int ToC_ParseCommand(int src_len0, o7_char src[/*len0*/], o7_bool *script) {
	int i, j, k;

	i = 0;
	while ((src[o7_ind(src_len0, i)] != 0x00u) && (src[o7_ind(src_len0, i)] != (o7_char)'.')) {
		i = o7_add(i, 1);
	}
	if (src[o7_ind(src_len0, i)] == (o7_char)'.') {
		j = o7_add(i, 1);
		ToC_ParseCommand_Empty(src_len0, src, &j);
		while (((o7_char)'a' <= src[o7_ind(src_len0, j)]) && (src[o7_ind(src_len0, j)] <= (o7_char)'z') || ((o7_char)'A' <= src[o7_ind(src_len0, j)]) && (src[o7_ind(src_len0, j)] <= (o7_char)'Z') || ((o7_char)'0' <= src[o7_ind(src_len0, j)]) && (src[o7_ind(src_len0, j)] <= (o7_char)'9')) {
			j = o7_add(j, 1);
		}
		k = j;
		ToC_ParseCommand_Empty(src_len0, src, &k);
		(*script) = src[o7_ind(src_len0, k)] != 0x00u;
	} else {
		(*script) = false;
	}
	return i;
}

static int ToC(struct CliParser_Args *args, int ret) {
	int arg, argDest, cpRet;

	O7_ASSERT(o7_in(ret, O7_SET(CliParser_ResultC_cnst, CliParser_ResultRun_cnst)));

	(*args).srcLen = 0;
	arg = 1;
	if (o7_cmp(CLI_count, arg) <= 0) {
		ret = CliParser_ErrNotEnoughArgs_cnst;
	} else if (!CliParser_GetParam(65536, (*args).src, &(*args).srcLen, &arg)) {
		ret = CliParser_ErrTooLongSourceName_cnst;
	} else {
		argDest = arg;
		(*args).srcLen = o7_add((*args).srcLen, 1);

		arg = o7_add(arg, (int)(ret != CliParser_ResultRun_cnst));
		cpRet = CopyPath(&(*args), &arg);
		if (cpRet != CliParser_ErrNo_cnst) {
			ret = cpRet;
		} else {
			(*args).srcNameEnd = ToC_ParseCommand(65536, (*args).src, &(*args).script);

			(*args).resPathLen = 0;
			(*args).resPath[0] = 0x00u;
			if ((ret != CliParser_ResultRun_cnst) && !CLI_Get(1024, (*args).resPath, &(*args).resPathLen, argDest)) {
				ret = CliParser_ErrTooLongOutName_cnst;
			}
		}
	}
	(*args).arg = arg;
	return ret;
}

extern o7_bool CliParser_Parse(struct CliParser_Args *args, int *ret) {
	int cmdLen;

	cmdLen = 0;
	V_Init(&(*args)._);
	if ((o7_cmp(CLI_count, 0) <= 0) || !CLI_Get(32, (*args).cmd, &cmdLen, 0)) {
		(*ret) = CliParser_ErrWrongArgs_cnst;
	} else if (o7_strcmp(32, (*args).cmd, 4, (o7_char *)"help") == 0) {
		(*ret) = CliParser_CmdHelp_cnst;
	} else if (o7_strcmp(32, (*args).cmd, 4, (o7_char *)"to-c") == 0) {
		(*ret) = ToC(&(*args), CliParser_ResultC_cnst);
	} else if (o7_strcmp(32, (*args).cmd, 6, (o7_char *)"to-bin") == 0) {
		(*ret) = ToC(&(*args), CliParser_ResultBin_cnst);
	} else if (o7_strcmp(32, (*args).cmd, 3, (o7_char *)"run") == 0) {
		(*ret) = ToC(&(*args), CliParser_ResultRun_cnst);
	} else {
		(*ret) = CliParser_ErrUnknownCommand_cnst;
	}
	return 0 <= (*ret);
}

extern void CliParser_init(void) {
	static int initialized = 0;
	if (0 == initialized) {
		CLI_init();
		StringStore_init();
		Platform_init();
		Log_init();
		GeneratorC_init();
	}
	++initialized;
}
