/* Generated by Vostok - Oberon-07 translator */

/*  Command line interface for Oberon-07 translator
 *  Copyright (C) 2016-2018 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_CliParser)
#define HEADER_GUARD_CliParser 1

#include "V.h"
#include "CLI.h"
#include "Utf8.h"
#include "StringStore.h"
#include "Platform.h"
#include "Log.h"
#include "GeneratorC.h"

#define CliParser_CmdHelp_cnst 1
/* TODO переименовать */
#define CliParser_ResultC_cnst 2
#define CliParser_ResultBin_cnst 3
#define CliParser_ResultRun_cnst 4

#define CliParser_ErrNo_cnst 0

#define CliParser_ErrWrongArgs_cnst (-10)
#define CliParser_ErrTooLongSourceName_cnst (-11)
#define CliParser_ErrTooLongOutName_cnst (-12)
#define CliParser_ErrOpenSource_cnst (-13)
#define CliParser_ErrOpenH_cnst (-14)
#define CliParser_ErrOpenC_cnst (-15)
#define CliParser_ErrUnknownCommand_cnst (-16)
#define CliParser_ErrNotEnoughArgs_cnst (-17)
#define CliParser_ErrTooLongModuleDirs_cnst (-18)
#define CliParser_ErrTooManyModuleDirs_cnst (-19)
#define CliParser_ErrTooLongCDirs_cnst (-20)
#define CliParser_ErrTooLongCc_cnst (-21)
#define CliParser_ErrTooLongTemp_cnst (-22)
#define CliParser_ErrCCompiler_cnst (-23)
#define CliParser_ErrTooLongRunArgs_cnst (-24)
#define CliParser_ErrUnexpectArg_cnst (-25)
#define CliParser_ErrUnknownInit_cnst (-26)
#define CliParser_ErrCantCreateOutDir_cnst (-27)
#define CliParser_ErrCantRemoveOutDir_cnst (-28)

typedef struct CliParser_Args {
	V_Base _;
	o7_char src[65536];
	int srcLen;
	o7_char cmd[32];
	o7_bool script;
	o7_char outC[1024];
	o7_char resPath[1024];
	o7_char tmp[1024];
	int resPathLen;
	int srcNameEnd;
	o7_char modPath[4096];
	o7_char cDirs[4096];
	o7_char cc[4096];
	int modPathLen;
	unsigned sing;
	int init;
	int arg;
} CliParser_Args;
#define CliParser_Args_tag V_Base_tag

extern void CliParser_Args_undef(struct CliParser_Args *r);

extern o7_bool CliParser_GetParam(int str_len0, o7_char str[/*len0*/], int *i, int *arg);

extern o7_bool CliParser_Parse(struct CliParser_Args *args, int *ret);

extern void CliParser_init(void);
#endif
