/* Generated by Vostok - Oberon-07 translator */

/*  Command line interface for Oberon-07 translator
 *  Copyright (C) 2016-2017 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_CliParser)
#define HEADER_GUARD_CliParser 1


#define CliParser_ResultC_cnst 0
#define CliParser_ResultBin_cnst 1
#define CliParser_ResultRun_cnst 2

#define CliParser_ErrNo_cnst 0

#define CliParser_ErrWrongArgs_cnst (-10)
#define CliParser_ErrTooLongSourceName_cnst (-11)
#define CliParser_ErrTooLongOutName_cnst (-12)
#define CliParser_ErrOpenSource_cnst (-13)
#define CliParser_ErrOpenH_cnst (-14)
#define CliParser_ErrOpenC_cnst (-15)
#define CliParser_ErrUnknownCommand_cnst (-16)
#define CliParser_ErrNotEnoughArgs_cnst (-17)
#define CliParser_ErrTooLongModuleDirs_cnst (-18)
#define CliParser_ErrTooManyModuleDirs_cnst (-19)
#define CliParser_ErrTooLongCDirs_cnst (-20)
#define CliParser_ErrTooLongCc_cnst (-21)
#define CliParser_ErrTooLongTemp_cnst (-22)
#define CliParser_ErrCCompiler_cnst (-23)
#define CliParser_ErrTooLongRunArgs_cnst (-24)
#define CliParser_ErrUnexpectArg_cnst (-25)
#define CliParser_ErrUnknownInit_cnst (-26)
#define CliParser_ErrCantCreateOutDir_cnst (-27)
#define CliParser_ErrCantRemoveOutDir_cnst (-28)

static inline void CliParser_init(void) { ; }
#endif
