/* Generated by Vostok - Oberon-07 translator */

/*  English messages for interface
 *  Copyright (C) 2018 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_Message)
#define HEADER_GUARD_Message 1

#include "OsEnv.h"
#include "Platform.h"
#include "MessageRu.h"
#include "MessageEn.h"

extern void Message_AstError(int code);

extern void Message_ParseError(int code);

extern void Message_Usage(void);

extern void Message_CliError(int err, int cmd_len0, o7_char cmd[/*len0*/]);

extern void Message_Text(int str_len0, o7_char str[/*len0*/]);

extern void Message_init(void);
#endif
