/* Generated by Vostok - Oberon-07 translator */

#include <stdbool.h>

#define O7_BOOL_UNDEFINED
#include <o7.h>

#include "Message.h"

static o7_bool ru = O7_BOOL_UNDEF;

extern void Message_AstError(int code) {
	if (o7_bl(ru)) {
		MessageRu_AstError(code);
	} else {
		MessageEn_AstError(code);
	}
}

extern void Message_ParseError(int code) {
	if (o7_bl(ru)) {
		MessageRu_ParseError(code);
	} else {
		MessageEn_ParseError(code);
	}
}

extern void Message_Usage(void) {
	if (o7_bl(ru)) {
		MessageRu_Usage();
	} else {
		MessageEn_Usage();
	}
}

extern void Message_CliError(int err, int cmd_len0, o7_char cmd[/*len0*/]) {
	if (o7_bl(ru)) {
		MessageRu_CliError(err, cmd_len0, cmd);
	} else {
		MessageEn_CliError(err, cmd_len0, cmd);
	}
}

extern void Message_Text(int str_len0, o7_char str[/*len0*/]) {
	if (o7_bl(ru)) {
		MessageRu_Text(str_len0, str);
	} else {
		MessageEn_Text(str_len0, str);
	}
}

static void InitLang(void) {
	o7_char lang[16];
	int ofs;
	memset(&lang, 0, sizeof(lang));

	ofs = 0;
	ru = Platform_Posix && OsEnv_Get(16, lang, &ofs, 4, (o7_char *)"LANG") && (o7_strcmp(16, lang, 11, (o7_char *)"ru_RU.UTF-8") == 0);
}

extern void Message_init(void) {
	static int initialized = 0;
	if (0 == initialized) {
		OsEnv_init();
		Platform_init();
		MessageRu_init();
		MessageEn_init();

		InitLang();
	}
	++initialized;
}

