/* Generated by Vostok - Oberon-07 translator */

#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <stdbool.h>

#define O7C_BOOL_UNDEFINED
#include <o7c.h>

#include "Out.h"

static o7c_bool success = O7C_BOOL_UNDEF;

extern void Out_String(int s_len0, o7c_char s[/*len0*/]) {
	int i = O7C_INT_UNDEF;

	i = 0;
	while (s[o7c_ind(s_len0, i)] != 0x00u) {
		i = o7c_add(i, 1);
	}
	success = o7c_cmp(i, CFiles_WriteChars(CFiles_out, s_len0, s, 0, i)) ==  0;
}

extern void Out_Char(o7c_char ch) {
	o7c_char s[1];
	memset(&s, 0, sizeof(s));

	s[0] = ch;
	success = o7c_cmp(1, CFiles_WriteChars(CFiles_out, 1, s, 0, 1)) ==  0;
}

extern void Out_Int(int x, int n) {
	o7c_char s[32];
	int i = O7C_INT_UNDEF;
	o7c_bool neg = O7C_BOOL_UNDEF;
	memset(&s, 0, sizeof(s));

	i = O7C_LEN(s);
	neg = false;
	if (o7c_cmp(x, 0) ==  0) {
		i = o7c_sub(i, 1);
		s[o7c_ind(32, i)] = (char unsigned)'0';
	} else {
		if (o7c_cmp(x, 0) <  0) {
			neg = true;
			x = o7c_sub(0, x);
		}
		while (o7c_cmp(x, 0) !=  0) {
			i = o7c_sub(i, 1);
			s[o7c_ind(32, i)] = o7c_chr(o7c_add((int)(char unsigned)'0', o7c_mod(x, 10)));
			x = o7c_div(x, 10);
		}
		if (o7c_bl(neg)) {
			i = o7c_sub(i, 1);
			s[o7c_ind(32, i)] = (char unsigned)'-';
		}
	}
	if (o7c_cmp(n, 0) <  0) {
		n = O7C_LEN(s);
	} else if (o7c_cmp(n, O7C_LEN(s)) >  0) {
		n = 0;
	} else {
		n = o7c_sub(O7C_LEN(s), n);
	}
	while (o7c_cmp(i, n) >  0) {
		i = o7c_sub(i, 1);
		s[o7c_ind(32, i)] = (char unsigned)' ';
	}
	success = o7c_cmp(o7c_sub(O7C_LEN(s), i), CFiles_WriteChars(CFiles_out, 32, s, i, o7c_sub(O7C_LEN(s), i))) ==  0;
}

extern void Out_Ln(void) {
	o7c_char s[2];
	memset(&s, 0, sizeof(s));

	s[0] = 0x0Du;
	s[1] = 0x0Au;
	success = (o7c_cmp(O7C_LEN(s), CFiles_WriteChars(CFiles_out, 2, s, 0, O7C_LEN(s))) ==  0) && CFiles_Flush(CFiles_out);
}

/* TODO */
extern void Out_Real(double x, int n) {
	o7c_char s[64];
	int i = O7C_INT_UNDEF, l = O7C_INT_UNDEF, e = O7C_INT_UNDEF, d = O7C_INT_UNDEF;
	o7c_bool sign = O7C_BOOL_UNDEF;
	double tens = O7C_DBL_UNDEF;
	memset(&s, 0, sizeof(s));

	i = O7C_LEN(s) / 2;
	if (x != x) {
		l = o7c_add(i, 2);
		s[o7c_ind(64, i)] = (char unsigned)'N';
		s[o7c_ind(64, o7c_add(i, 1))] = (char unsigned)'a';
		s[o7c_ind(64, o7c_add(i, 2))] = (char unsigned)'N';
	} else if ((x == 0.0) || (x ==  - 0.0)) {
		l = o7c_add(i, 2);
		s[o7c_ind(64, i)] = (char unsigned)'0';
		s[o7c_ind(64, o7c_add(i, 1))] = (char unsigned)'.';
		s[o7c_ind(64, o7c_add(i, 2))] = (char unsigned)'0';
		if (x < 0.0) {
			i = o7c_sub(i, 1);
			s[o7c_ind(64, i)] = (char unsigned)'-';
		}
	} else {
		sign = x < 0.0;
		l = i;
		if (o7c_bl(sign)) {
			s[o7c_ind(64, l)] = (char unsigned)'-';
			l = o7c_add(l, 1);
			x = o7c_fsub(0, x);
		}
		if (x < 1.0) {
			e =  - 1;
			tens = 10.0;
			while (o7c_fmul(x, tens) < 1.0) {
				e = o7c_sub(e, 1);
				tens = o7c_fmul(tens, 10.0);
			}
			x = o7c_fmul(x, tens);
		} else if (10.0 <= x) {
			e = 1;
			tens = 10.0;
			while ((o7c_fdiv(x, tens) >= 10.0) && (o7c_cmp(e, 307) <=  0)) {
				e = o7c_add(e, 1);
				tens = o7c_fmul(tens, 10.0);
			}
			x = o7c_fdiv(x, tens);
		} else {
			assert((1.0 <= x) && (x < 10.0));
			e = 0;
		}
		if (o7c_cmp(e, 307) >  0) {
			s[o7c_ind(64, l)] = (char unsigned)'i';
			s[o7c_ind(64, o7c_add(l, 1))] = (char unsigned)'n';
			s[o7c_ind(64, o7c_add(l, 2))] = (char unsigned)'f';
			l = o7c_add(l, 2);
		} else {
			s[o7c_ind(64, l)] = o7c_chr(o7c_add((int)(char unsigned)'0', (int)x));
			l = o7c_add(l, 1);
			s[o7c_ind(64, l)] = (char unsigned)'.';
			if (o7c_cmp(o7c_mod((int)(o7c_fmul(x, 10.0)), 10), 0) ==  0) {
				l = o7c_add(l, 1);
				s[o7c_ind(64, l)] = (char unsigned)'0';
			} else {
				while ((o7c_cmp(l, O7C_LEN(s) - 6) <  0) && (o7c_cmp(o7c_mod((int)(o7c_fmul(x, 10.0)), 10), 0) !=  0)) {
					x = o7c_fsub(x, (double)(o7c_mod((int)x, 10)));
					x = o7c_fmul(x, 10.0);
					l = o7c_add(l, 1);
					s[o7c_ind(64, l)] = o7c_chr(o7c_add((int)(char unsigned)'0', o7c_mod((int)x, 10)));
				}
			}
			if (o7c_cmp(e, 0) !=  0) {
				s[o7c_ind(64, o7c_add(l, 1))] = (char unsigned)'E';
				l = o7c_add(l, 2);
				if (o7c_cmp(e, 0) <  0) {
					e = o7c_sub(0, e);
					s[o7c_ind(64, l)] = (char unsigned)'-';
				} else {
					s[o7c_ind(64, l)] = (char unsigned)'+';
				}
				d = 100;
				while (o7c_cmp(e, d) <  0) {
					d = o7c_div(d, 10);
				}
				do {
					l = o7c_add(l, 1);
					s[o7c_ind(64, l)] = o7c_chr(o7c_add((int)(char unsigned)'0', o7c_div(e, d)));
					e = o7c_mod(e, d);
					d = o7c_div(d, 10);
				} while (!(o7c_cmp(d, 0) ==  0));
			}
		}
	}
	if (o7c_cmp(o7c_add(l, 1), n) >  0) {
		n = o7c_sub(o7c_add(l, 1), n);
	} else {
		n = 0;
	}
	while (o7c_cmp(n, i) <  0) {
		i = o7c_sub(i, 1);
		s[o7c_ind(64, i)] = (char unsigned)' ';
	}
	success = o7c_cmp(o7c_add(o7c_sub(l, i), 1), CFiles_WriteChars(CFiles_out, 64, s, i, o7c_add(o7c_sub(l, i), 1))) ==  0;
}

extern void Out_Open(void) {
	success = true;
}

extern void Out_init(void) {
	static int initialized = 0;
	if (0 == initialized) {
		CFiles_init();

	}
	++initialized;
}

