/* Generated by Vostok - Oberon-07 translator */

/* Copyright 2017 ComdivByZero
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#if !defined(HEADER_GUARD_Out)
#define HEADER_GUARD_Out

#include "CFiles.h"

extern void Out_String(int s_len0, o7c_char s[/*len0*/]);

extern void Out_Char(o7c_char ch);

extern void Out_Int(int x, int n);

extern void Out_Ln(void);

extern void Out_Real(double x, int n);

extern void Out_Open(void);

extern void Out_init(void);
#endif
