/* Generated by Vostok - Oberon-07 translator */

/*  Parser of Oberon-07 modules
 *  Copyright (C) 2017 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_PlatformExec)
#define HEADER_GUARD_PlatformExec 1

#include "V.h"
#include "Utf8.h"
#include "OsExec.h"
#include "Log.h"
#include "Platform.h"

#define PlatformExec_CodeSize_cnst 65536

#define PlatformExec_Ok_cnst 0

typedef struct PlatformExec_Code {
	V_Base _;
	o7_char buf[PlatformExec_CodeSize_cnst];
	int len;
} PlatformExec_Code;
#define PlatformExec_Code_tag V_Base_tag

extern void PlatformExec_Code_undef(struct PlatformExec_Code *r);

extern o7_bool PlatformExec_Init(struct PlatformExec_Code *c, int name_len0, o7_char name[/*len0*/]);

extern o7_bool PlatformExec_Add(struct PlatformExec_Code *c, int arg_len0, o7_char arg[/*len0*/], int ofs);

extern o7_bool PlatformExec_AddClean(struct PlatformExec_Code *c, int arg_len0, o7_char arg[/*len0*/]);

extern o7_bool PlatformExec_FirstPart(struct PlatformExec_Code *c, int arg_len0, o7_char arg[/*len0*/]);

extern o7_bool PlatformExec_AddPart(struct PlatformExec_Code *c, int arg_len0, o7_char arg[/*len0*/]);

extern o7_bool PlatformExec_LastPart(struct PlatformExec_Code *c, int arg_len0, o7_char arg[/*len0*/]);

extern int PlatformExec_Do(struct PlatformExec_Code *c);

extern void PlatformExec_Log(struct PlatformExec_Code *c);

extern void PlatformExec_init(void);
#endif
