/* Generated by Vostok - Oberon-07 translator */

#include <stdbool.h>

#define O7_BOOL_UNDEFINED
#include <o7.h>

#include "Scanner.h"

#define NewPage_cnst 0x0Cu

#define IntMax_cnst 2147483647
#define CharMax_cnst 0xFFu
#define RealScaleMax_cnst 512

#define Scanner_Scanner_tag V_Base_tag
extern void Scanner_Scanner_undef(struct Scanner_Scanner *r) {
	V_Base_undef(&r->_);
	r->in_ = NULL;
	r->line = O7_INT_UNDEF;
	r->column = O7_INT_UNDEF;
	r->tabs = O7_INT_UNDEF;
	memset(&r->buf, 0, sizeof(r->buf));
	r->ind = O7_INT_UNDEF;
	r->lexStart = O7_INT_UNDEF;
	r->lexEnd = O7_INT_UNDEF;
	r->lexLen = O7_INT_UNDEF;
	r->emptyLines = O7_INT_UNDEF;
	r->isReal = O7_BOOL_UNDEF;
	r->isChar = O7_BOOL_UNDEF;
	r->integer = O7_INT_UNDEF;
	r->real = O7_DBL_UNDEF;
	r->commentOfs = O7_INT_UNDEF;
	r->commentEnd = O7_INT_UNDEF;
}

typedef o7_bool (*Suit)(o7_char ch);
typedef int (*SuitDigit)(o7_char ch);

static void PreInit(struct Scanner_Scanner *s) {
	V_Init(&(*s)._);
	(*s).column = 0;
	(*s).tabs = 0;
	(*s).line = 0;
	(*s).commentOfs =  - 1;
}

extern void Scanner_Init(struct Scanner_Scanner *s, struct VDataStream_In *in_) {
	O7_ASSERT(in_ != NULL);
	PreInit(&(*s));
	(*s).in_ = in_;
	(*s).ind = O7_LEN((*s).buf) - 1;
	(*s).buf[0] = 0x0Cu;
	(*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)] = 0x0Cu;
}

extern o7_bool Scanner_InitByString(struct Scanner_Scanner *s, int in__len0, o7_char in_[/*len0*/]) {
	int len;
	o7_bool ret;

	PreInit(&(*s));
	(*s).in_ = NULL;
	(*s).ind = 0;
	(*s).buf[0] = (o7_char)' ';

	len = 1;
	ret = StringStore_CopyCharsNull(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &len, in__len0, in_);
	(*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, len)] = 0x04u;
	return ret;
}

static void FillBuf(int buf_len0, o7_char buf[/*len0*/], int *ind, struct VDataStream_In *in_, o7_tag_t in__tag);
static void FillBuf_Normalize(int buf_len0, o7_char buf[/*len0*/], int i, int end) {
	while (i < end) {
		if ((buf[o7_ind(buf_len0, i)] == 0x0Cu) || (buf[o7_ind(buf_len0, i)] == 0x04u)) {
			buf[o7_ind(buf_len0, i)] = 0x16u;
		}
		i = o7_add(i, 1);
	}
}

static void FillBuf(int buf_len0, o7_char buf[/*len0*/], int *ind, struct VDataStream_In *in_, o7_tag_t in__tag) {
	int size;

	O7_ASSERT((buf_len0 % 2 == 1));
	if (o7_mod((*ind), (o7_div(buf_len0, 2))) != 0) {
		Log_StrLn(77, (o7_char *)"индекс новой страницы в неожиданном месте");
		O7_ASSERT(buf[o7_ind(buf_len0, (*ind))] == 0x0Cu);
		buf[o7_ind(buf_len0, (*ind))] = 0x00u;
	} else {
		(*ind) = o7_mod((*ind), (o7_sub(buf_len0, 1)));
		if (buf[o7_ind(buf_len0, (*ind))] == 0x0Cu) {
			size = VDataStream_ReadChars(&(*in_), in__tag, buf_len0, buf, (*ind), o7_div(buf_len0, 2));
			FillBuf_Normalize(buf_len0, buf, (*ind), o7_add((*ind), size));
			if (size == o7_div(buf_len0, 2)) {
				buf[o7_ind(buf_len0, o7_mod((o7_add((*ind), o7_div(buf_len0, 2))), (o7_sub(buf_len0, 1))))] = 0x0Cu;
			} else {
				buf[o7_ind(buf_len0, o7_add((*ind), size))] = 0x04u;
			}
		}
	}
}

/* TODO убрать*/
static o7_char ScanChar(struct Scanner_Scanner *s) {
	o7_char ch;

	(*s).ind = o7_add((*s).ind, 1);
	ch = (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)];
	if (ch == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &(*s).ind, &(*O7_REF((*s).in_)), NULL);
		ch = (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)];
	}
	return ch;
}

static o7_char Lookup(struct Scanner_Scanner *s) {
	int i;

	i = o7_add((*s).ind, 1);
	if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
	}
	return (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)];
}

static void ScanChars(struct Scanner_Scanner *s, Suit suit) {
	while (1) if (suit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)])) {
		(*s).ind = o7_add((*s).ind, 1);
	} else if (((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)] == 0x0Cu) && ((*s).in_ != NULL)) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &(*s).ind, &(*O7_REF((*s).in_)), NULL);
	} else break;
}

static o7_bool IsDigit(o7_char ch) {
	return ((o7_char)'0' <= ch) && (ch <= (o7_char)'9');
}

static o7_bool IsHexDigit(o7_char ch) {
	return ((o7_char)'0' <= ch) && (ch <= (o7_char)'9') || ((o7_char)'A' <= ch) && (ch <= (o7_char)'F');
}

static int ValDigit(o7_char ch) {
	int i;

	if ((ch >= (o7_char)'0') && (ch <= (o7_char)'9')) {
		i = o7_sub((int)ch, (int)(o7_char)'0');
	} else {
		i =  - 1;
	}
	return i;
}

static int ValHexDigit(o7_char ch) {
	int i;

	if ((ch >= (o7_char)'0') && (ch <= (o7_char)'9')) {
		i = o7_sub((int)ch, (int)(o7_char)'0');
	} else if ((ch >= (o7_char)'A') && (ch <= (o7_char)'F')) {
		i = o7_sub(o7_add(10, (int)ch), (int)(o7_char)'A');
	} else {
		i =  - 1;
	}
	return i;
}

static int SNumber(struct Scanner_Scanner *s);
static void SNumber_Val(struct Scanner_Scanner *s, int *lex, int capacity, SuitDigit valDigit) {
	int d, val, i;

	val = 0;
	i = o7_int((*s).lexStart);
	d = valDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	/*Log.Str("IntMax "); Log.Int(IntMax); Log.Ln;*/
	while (1) if (d >= 0) {
		if (o7_div(IntMax_cnst, capacity) >= val) {
			val = o7_mul(val, capacity);
			if (o7_sub(IntMax_cnst, d) >= val) {
				val = o7_add(val, d);
			} else {
				(*lex) = Scanner_ErrNumberTooBig_cnst;
			}
		} else {
			(*lex) = Scanner_ErrNumberTooBig_cnst;
		}
		i = o7_add(i, 1);
		d = valDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		i = 0;
		d = valDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	} else break;
	(*s).integer = val;
}

static void SNumber_ValReal(struct Scanner_Scanner *s, int *lex) {
	/* TODO */
	int i, d, scale;
	o7_bool scMinus;
	double val, t;

	val = 1.0;
	i = o7_int((*s).lexStart);
	d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	while (1) if (d >= 0) {
		val = o7_fadd(o7_fmul(val, 10.0), o7_flt(d));
		i = o7_add(i, 1);
		d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		i = 0;
		d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	} else break;
	/* skip dot */
	i = o7_add(i, 1);
	t = 10.0;
	d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	while (1) if (d >= 0) {
		val = o7_fadd(val, o7_fdiv(o7_flt(d), t));
		t = o7_fmul(t, 10.0);
		i = o7_add(i, 1);
		d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
		d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
	} else break;
	if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)'E') {
		i = o7_add(i, 1);
		if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
			FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
		}
		scMinus = (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)'-';
		if (scMinus || ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)'+')) {
			i = o7_add(i, 1);
			if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
				FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
			}
		}
		d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
		if (d >= 0) {
			scale = 0;
			while (1) if (d >= 0) {
				if (scale < IntMax_cnst / 10) {
					scale = o7_add(o7_mul(scale, 10), d);
				}
				i = o7_add(i, 1);
				d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
			} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
				FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
				d = ValDigit((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)]);
			} else break;
			if (scale <= RealScaleMax_cnst) {
				/* TODO */
				while (scale > 0) {
					if (scMinus) {
						val = o7_fmul(val, 10.0);
					} else {
						val = o7_fdiv(val, 10.0);
					}
					scale = o7_sub(scale, 1);
				}
			} else {
				(*lex) = Scanner_ErrRealScaleTooBig_cnst;
			}
		} else {
			(*lex) = Scanner_ErrExpectDigitInScale_cnst;
		}
	}
	(*s).ind = i;
	(*s).real = val;
}

static int SNumber(struct Scanner_Scanner *s) {
	int lex;
	o7_char ch;

	lex = Scanner_Number_cnst;
	ScanChars(&(*s), IsDigit);
	ch = (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)];
	(*s).isReal = (ch == (o7_char)'.') && (Lookup(&(*s)) != (o7_char)'.');
	if (o7_bl((*s).isReal)) {
		(*s).ind = o7_add((*s).ind, 1);
		SNumber_ValReal(&(*s), &lex);
	} else if ((ch >= (o7_char)'A') && (ch <= (o7_char)'F') || (ch == (o7_char)'H') || (ch == (o7_char)'X')) {
		ScanChars(&(*s), IsHexDigit);
		ch = (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)];
		SNumber_Val(&(*s), &lex, 16, ValHexDigit);
		if (ch == (o7_char)'X') {
			if (o7_cmp((*s).integer, (int)0xFFu) <= 0) {
				lex = Scanner_String_cnst;
				(*s).isChar = true;
			} else {
				lex = Scanner_ErrNumberTooBig_cnst;
			}
		} else if (ch != (o7_char)'H') {
			lex = Scanner_ErrExpectHOrX_cnst;
		}
		if ((ch == (o7_char)'X') || (ch == (o7_char)'H')) {
			(*s).ind = o7_add((*s).ind, 1);
		}
	} else {
		SNumber_Val(&(*s), &lex, 10, ValDigit);
	}
	Log_Str(13, (o7_char *)"Number lex = ");
	Log_Int(lex);
	Log_Ln();
	return lex;
}

static o7_bool IsWordEqual(int str_len0, o7_char str[/*len0*/], int buf_len0, o7_char buf[/*len0*/], int ind, int end) {
	int i, j;

	O7_ASSERT(str_len0 <= o7_div(buf_len0, 2));
	j = 1;
	i = o7_add(ind, 1);
	while (1) if ((j < str_len0) && (buf[o7_ind(buf_len0, i)] == str[o7_ind(str_len0, j)])) {
		i = o7_add(i, 1);
		j = o7_add(j, 1);
	} else if (buf[o7_ind(buf_len0, i)] == 0x0Cu) {
		i = 0;
	} else break;
	return (buf[o7_ind(buf_len0, i)] == 0x08u) && ((j == str_len0) || (str[o7_ind(str_len0, j)] == 0x00u));
}

static o7_bool CheckPredefined_Eq(int str_len0, o7_char str[/*len0*/], int buf_len0, o7_char buf[/*len0*/], int begin, int end) {
	return IsWordEqual(str_len0, str, buf_len0, buf, begin, end);
}

static int CheckPredefined_O(int str_len0, o7_char str[/*len0*/], int buf_len0, o7_char buf[/*len0*/], int begin, int end, int id) {
	if (!IsWordEqual(str_len0, str, buf_len0, buf, begin, end)) {
		id = Scanner_Ident_cnst;
	}
	return id;
}

static int CheckPredefined_T(int s1_len0, o7_char s1[/*len0*/], int buf_len0, o7_char buf[/*len0*/], int begin, int end, int id1, int s2_len0, o7_char s2[/*len0*/], int id2) {
	if (IsWordEqual(s1_len0, s1, buf_len0, buf, begin, end)) {
		id2 = id1;
	} else if (!IsWordEqual(s2_len0, s2, buf_len0, buf, begin, end)) {
		id2 = Scanner_Ident_cnst;
	}
	return id2;
}

extern int Scanner_CheckPredefined(int buf_len0, o7_char buf[/*len0*/], int begin, int end) {
	int id;
	o7_char save;

	save = buf[o7_ind(buf_len0, end)];
	buf[o7_ind(buf_len0, end)] = 0x08u;
	{ int o7_case_expr = buf[o7_ind(buf_len0, begin)];
		switch (o7_case_expr) {
		case 65:
			if (CheckPredefined_Eq(3, (o7_char *)"ABS", buf_len0, buf, begin, end)) {
				id = Scanner_Abs_cnst;
			} else {
				id = CheckPredefined_T(3, (o7_char *)"ASR", buf_len0, buf, begin, end, Scanner_Asr_cnst, 6, (o7_char *)"ASSERT", Scanner_Assert_cnst);
			}
			break;
		case 66:
			id = CheckPredefined_T(7, (o7_char *)"BOOLEAN", buf_len0, buf, begin, end, Scanner_Boolean_cnst, 4, (o7_char *)"BYTE", Scanner_Byte_cnst);
			break;
		case 67:
			id = CheckPredefined_T(4, (o7_char *)"CHAR", buf_len0, buf, begin, end, Scanner_Char_cnst, 3, (o7_char *)"CHR", Scanner_Chr_cnst);
			break;
		case 68:
			id = CheckPredefined_O(3, (o7_char *)"DEC", buf_len0, buf, begin, end, Scanner_Dec_cnst);
			break;
		case 69:
			id = CheckPredefined_O(4, (o7_char *)"EXCL", buf_len0, buf, begin, end, Scanner_Excl_cnst);
			break;
		case 70:
			id = CheckPredefined_T(5, (o7_char *)"FLOOR", buf_len0, buf, begin, end, Scanner_Floor_cnst, 3, (o7_char *)"FLT", Scanner_Flt_cnst);
			break;
		case 73:
			if (CheckPredefined_Eq(3, (o7_char *)"INC", buf_len0, buf, begin, end)) {
				id = Scanner_Inc_cnst;
			} else {
				id = CheckPredefined_T(4, (o7_char *)"INCL", buf_len0, buf, begin, end, Scanner_Incl_cnst, 7, (o7_char *)"INTEGER", Scanner_Integer_cnst);
			}
			break;
		case 76:
			id = CheckPredefined_T(3, (o7_char *)"LEN", buf_len0, buf, begin, end, Scanner_Len_cnst, 3, (o7_char *)"LSL", Scanner_Lsl_cnst);
			break;
		case 78:
			id = CheckPredefined_O(3, (o7_char *)"NEW", buf_len0, buf, begin, end, Scanner_New_cnst);
			break;
		case 79:
			id = CheckPredefined_T(3, (o7_char *)"ODD", buf_len0, buf, begin, end, Scanner_Odd_cnst, 3, (o7_char *)"ORD", Scanner_Ord_cnst);
			break;
		case 80:
			id = CheckPredefined_O(4, (o7_char *)"PACK", buf_len0, buf, begin, end, Scanner_Pack_cnst);
			break;
		case 82:
			id = CheckPredefined_T(4, (o7_char *)"REAL", buf_len0, buf, begin, end, Scanner_Real_cnst, 3, (o7_char *)"ROR", Scanner_Ror_cnst);
			break;
		case 83:
			id = CheckPredefined_O(3, (o7_char *)"SET", buf_len0, buf, begin, end, Scanner_Set_cnst);
			break;
		case 85:
			id = CheckPredefined_O(4, (o7_char *)"UNPK", buf_len0, buf, begin, end, Scanner_Unpk_cnst);
			break;
		default:
			if ((o7_case_expr == 71) || (o7_case_expr == 72) || (o7_case_expr == 74) || (o7_case_expr == 75) || (o7_case_expr == 77) || (o7_case_expr == 81) || (o7_case_expr == 84) || (86 <= o7_case_expr && o7_case_expr <= 90) || (97 <= o7_case_expr && o7_case_expr <= 122)) {
				id = Scanner_Ident_cnst;
			} else o7_case_fail(o7_case_expr);
			break;
		}
	}
	buf[o7_ind(buf_len0, end)] = save;
	return id;
}

static int CheckWord(int buf_len0, o7_char buf[/*len0*/], int ind, int end);
static o7_bool CheckWord_Eq(int str_len0, o7_char str[/*len0*/], int buf_len0, o7_char buf[/*len0*/], int ind, int end) {
	return IsWordEqual(str_len0, str, buf_len0, buf, ind, end);
}

static void CheckWord_O(int *lex, int str_len0, o7_char str[/*len0*/], int buf_len0, o7_char buf[/*len0*/], int ind, int end, int l) {
	if (IsWordEqual(str_len0, str, buf_len0, buf, ind, end)) {
		(*lex) = l;
	} else {
		(*lex) = Scanner_Ident_cnst;
	}
}

static void CheckWord_T(int *lex, int s1_len0, o7_char s1[/*len0*/], int l1, int s2_len0, o7_char s2[/*len0*/], int l2, int buf_len0, o7_char buf[/*len0*/], int ind, int end) {
	if (IsWordEqual(s1_len0, s1, buf_len0, buf, ind, end)) {
		(*lex) = l1;
	} else if (IsWordEqual(s2_len0, s2, buf_len0, buf, ind, end)) {
		(*lex) = l2;
	} else {
		(*lex) = Scanner_Ident_cnst;
	}
}

static int CheckWord(int buf_len0, o7_char buf[/*len0*/], int ind, int end) {
	int lex;
	o7_char save;

	save = buf[o7_ind(buf_len0, end)];
	buf[o7_ind(buf_len0, end)] = 0x08u;
	/*
	Log.Str("lexStart "); Log.Int(ind); Log.Str(" ");
	Log.Int(ORD(buf[ind])); Log.Ln;
	*/
	{ int o7_case_expr = buf[o7_ind(buf_len0, ind)];
		switch (o7_case_expr) {
		case 65:
			CheckWord_O(&lex, 5, (o7_char *)"ARRAY", buf_len0, buf, ind, end, Scanner_Array_cnst);
			break;
		case 66:
			CheckWord_T(&lex, 5, (o7_char *)"BEGIN", Scanner_Begin_cnst, 2, (o7_char *)"BY", Scanner_By_cnst, buf_len0, buf, ind, end);
			break;
		case 67:
			CheckWord_T(&lex, 4, (o7_char *)"CASE", Scanner_Case_cnst, 5, (o7_char *)"CONST", Scanner_Const_cnst, buf_len0, buf, ind, end);
			break;
		case 68:
			CheckWord_T(&lex, 3, (o7_char *)"DIV", Scanner_Div_cnst, 2, (o7_char *)"DO", Scanner_Do_cnst, buf_len0, buf, ind, end);
			break;
		case 69:
			if (CheckWord_Eq(4, (o7_char *)"ELSE", buf_len0, buf, ind, end)) {
				lex = Scanner_Else_cnst;
			} else {
				CheckWord_T(&lex, 5, (o7_char *)"ELSIF", Scanner_Elsif_cnst, 3, (o7_char *)"END", Scanner_End_cnst, buf_len0, buf, ind, end);
			}
			break;
		case 70:
			CheckWord_T(&lex, 5, (o7_char *)"FALSE", Scanner_False_cnst, 3, (o7_char *)"FOR", Scanner_For_cnst, buf_len0, buf, ind, end);
			break;
		case 73:
			if (CheckWord_Eq(2, (o7_char *)"IF", buf_len0, buf, ind, end)) {
				lex = Scanner_If_cnst;
			} else if (CheckWord_Eq(6, (o7_char *)"IMPORT", buf_len0, buf, ind, end)) {
				lex = Scanner_Import_cnst;
			} else {
				CheckWord_T(&lex, 2, (o7_char *)"IN", Scanner_In_cnst, 2, (o7_char *)"IS", Scanner_Is_cnst, buf_len0, buf, ind, end);
			}
			break;
		case 77:
			CheckWord_T(&lex, 3, (o7_char *)"MOD", Scanner_Mod_cnst, 6, (o7_char *)"MODULE", Scanner_Module_cnst, buf_len0, buf, ind, end);
			break;
		case 78:
			CheckWord_O(&lex, 3, (o7_char *)"NIL", buf_len0, buf, ind, end, Scanner_Nil_cnst);
			break;
		case 79:
			CheckWord_T(&lex, 2, (o7_char *)"OF", Scanner_Of_cnst, 2, (o7_char *)"OR", Scanner_Or_cnst, buf_len0, buf, ind, end);
			break;
		case 80:
			CheckWord_T(&lex, 7, (o7_char *)"POINTER", Scanner_Pointer_cnst, 9, (o7_char *)"PROCEDURE", Scanner_Procedure_cnst, buf_len0, buf, ind, end);
			break;
		case 82:
			if (CheckWord_Eq(6, (o7_char *)"RECORD", buf_len0, buf, ind, end)) {
				lex = Scanner_Record_cnst;
			} else {
				CheckWord_T(&lex, 6, (o7_char *)"REPEAT", Scanner_Repeat_cnst, 6, (o7_char *)"RETURN", Scanner_Return_cnst, buf_len0, buf, ind, end);
			}
			break;
		case 84:
			if (CheckWord_Eq(4, (o7_char *)"THEN", buf_len0, buf, ind, end)) {
				lex = Scanner_Then_cnst;
			} else if (CheckWord_Eq(2, (o7_char *)"TO", buf_len0, buf, ind, end)) {
				lex = Scanner_To_cnst;
			} else {
				CheckWord_T(&lex, 4, (o7_char *)"TRUE", Scanner_True_cnst, 4, (o7_char *)"TYPE", Scanner_Type_cnst, buf_len0, buf, ind, end);
			}
			break;
		case 85:
			CheckWord_O(&lex, 5, (o7_char *)"UNTIL", buf_len0, buf, ind, end, Scanner_Until_cnst);
			break;
		case 86:
			CheckWord_O(&lex, 3, (o7_char *)"VAR", buf_len0, buf, ind, end, Scanner_Var_cnst);
			break;
		case 87:
			CheckWord_O(&lex, 5, (o7_char *)"WHILE", buf_len0, buf, ind, end, Scanner_While_cnst);
			break;
		default:
			if ((0 <= o7_case_expr && o7_case_expr <= 64) || (o7_case_expr == 71) || (o7_case_expr == 72) || (74 <= o7_case_expr && o7_case_expr <= 76) || (o7_case_expr == 81) || (o7_case_expr == 83) || (88 <= o7_case_expr && o7_case_expr <= 255)) {
				lex = Scanner_Ident_cnst;
			} else o7_case_fail(o7_case_expr);
			break;
		}
	}
	buf[o7_ind(buf_len0, end)] = save;
	return lex;
}

static o7_bool IsLetterOrDigit(o7_char ch) {
	return (ch >= (o7_char)'A') && (ch <= (o7_char)'Z') || (ch >= (o7_char)'a') && (ch <= (o7_char)'z') || (ch >= (o7_char)'0') && (ch <= (o7_char)'9');
}

static int SWord(struct Scanner_Scanner *s) {
	int len, l;

	ScanChars(&(*s), IsLetterOrDigit);
	len = o7_add(o7_sub((*s).ind, (*s).lexStart), o7_mul((int)(o7_cmp((*s).ind, (*s).lexStart) < 0), (O7_LEN((*s).buf) - 1)));
	O7_ASSERT(0 < len);
	if (len <= TranslatorLimits_LenName_cnst) {
		l = CheckWord(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, (*s).lexStart, (*s).ind);
	} else {
		l = Scanner_ErrWordLenTooBig_cnst;
	}
	return l;
}

static o7_bool ScanBlank(struct Scanner_Scanner *s) {
	int start, i, comment, commentsCount;

	i = o7_int((*s).ind);
	/*Log.Str("ScanBlank ind = "); Log.Int(i); Log.Ln;*/
	O7_ASSERT(0 <= i);
	start = i;
	comment = 0;
	commentsCount = 0;
	(*s).emptyLines =  - 1;
	while (1) if (((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)' ') || ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Du)) {
		i = o7_add(i, 1);
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x09u) {
		i = o7_add(i, 1);
		(*s).tabs = o7_add((*s).tabs, 1);
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Au) {
		(*s).line = o7_add((*s).line, 1);
		(*s).emptyLines = o7_add((*s).emptyLines, 1);
		(*s).column = 0;
		(*s).tabs = 0;
		i = o7_add(i, 1);
		start = i;
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
		start = o7_sub(start, o7_mul((int)(i == 0), (O7_LEN((*s).buf) - 1)));
	} else if (((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)'(') && (comment >= 0)) {
		(*s).ind = i;
		if (ScanChar(&(*s)) == (o7_char)'*') {
			start = o7_sub(start, o7_mul((int)(o7_cmp((*s).ind, start) < 0), (O7_LEN((*s).buf) - 1)));
			(*s).ind = o7_add((*s).ind, 1);
			comment = o7_add(comment, 1);
			commentsCount = o7_add(commentsCount, 1);
			if (commentsCount == 1) {
				if (o7_cmp((*s).ind, O7_LEN((*s).buf) - 1) == 0) {
					(*s).commentOfs = 0;
				} else {
					(*s).commentOfs = o7_int((*s).ind);
				}
			}
		} else if (comment == 0) {
			(*s).ind = i;
			comment =  - 1;
		}
		i = o7_int((*s).ind);
	} else if ((comment > 0) && ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] != 0x00u)) {
		/* & ~blank */
		if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)'*') {
			(*s).ind = i;
			if (ScanChar(&(*s)) == (o7_char)')') {
				start = o7_sub(start, o7_mul((int)(o7_cmp((*s).ind, start) < 0), (O7_LEN((*s).buf) - 1)));
				comment = o7_sub(comment, 1);
				if (comment == 0) {
					(*s).commentEnd = i;
					(*s).emptyLines =  - 1;
				}
				i = o7_int((*s).ind);
			}
		}
		i = o7_add(i, 1);
	} else break;
	(*s).column = o7_add((*s).column, (o7_sub(i, start)));
	O7_ASSERT(o7_cmp(0, (*s).column) <= 0);
	(*s).ind = i;
	return comment <= 0;
}

static int ScanString(struct Scanner_Scanner *s) {
	int l, i, j, count;

	i = o7_add((*s).ind, 1);
	if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
	}
	j = i;
	count = 0;
	while (1) if (((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] != (o7_char)'"') && (((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] >= (o7_char)' ') || ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x09u))) {
		i = o7_add(i, 1);
		count = o7_add(count, 1);
	} else if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &i, &(*O7_REF((*s).in_)), NULL);
	} else break;
	(*s).isChar = false;
	if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, i)] == (o7_char)'"') {
		l = Scanner_String_cnst;
		if (count == 1) {
			(*s).isChar = true;
			(*s).integer = (int)(*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, j)];
		}
		i = o7_mod((o7_add(i, 1)), (O7_LEN((*s).buf) - 1));
	} else {
		l = Scanner_ErrExpectDQuote_cnst;
	}
	(*s).ind = i;
	return l;
}

static void Next_L(int *lex, struct Scanner_Scanner *s, int l) {
	(*s).ind = o7_add((*s).ind, 1);
	(*lex) = l;
}

static void Next_Li(int *lex, struct Scanner_Scanner *s, o7_char ch, int then, int else_) {
	(*s).ind = o7_add((*s).ind, 1);
	if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)] == 0x0Cu) {
		FillBuf(Scanner_BlockSize_cnst * 2 + 1, (*s).buf, &(*s).ind, &(*O7_REF((*s).in_)), NULL);
	}
	if ((*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)] == ch) {
		(*lex) = then;
		(*s).ind = o7_add((*s).ind, 1);
	} else {
		(*lex) = else_;
	}
}

extern int Scanner_Next(struct Scanner_Scanner *s) {
	int lex;

	if (!ScanBlank(&(*s))) {
		lex = Scanner_ErrUnclosedComment_cnst;
	} else {
		(*s).lexStart = o7_int((*s).ind);
		{ int o7_case_expr = (*s).buf[o7_ind(Scanner_BlockSize_cnst * 2 + 1, (*s).ind)];
			switch (o7_case_expr) {
			case 4:
				lex = Scanner_EndOfFile_cnst;
				break;
			case 43:
				Next_L(&lex, &(*s), Scanner_Plus_cnst);
				break;
			case 45:
				Next_L(&lex, &(*s), Scanner_Minus_cnst);
				break;
			case 42:
				Next_L(&lex, &(*s), Scanner_Asterisk_cnst);
				break;
			case 47:
				Next_L(&lex, &(*s), Scanner_Slash_cnst);
				break;
			case 46:
				Next_Li(&lex, &(*s), (o7_char)'.', Scanner_Range_cnst, Scanner_Dot_cnst);
				break;
			case 44:
				Next_L(&lex, &(*s), Scanner_Comma_cnst);
				break;
			case 58:
				Next_Li(&lex, &(*s), (o7_char)'=', Scanner_Assign_cnst, Scanner_Colon_cnst);
				break;
			case 59:
				Next_L(&lex, &(*s), Scanner_Semicolon_cnst);
				break;
			case 94:
				Next_L(&lex, &(*s), Scanner_Dereference_cnst);
				break;
			case 61:
				Next_L(&lex, &(*s), Scanner_Equal_cnst);
				break;
			case 35:
				Next_L(&lex, &(*s), Scanner_Inequal_cnst);
				break;
			case 126:
				Next_L(&lex, &(*s), Scanner_Negate_cnst);
				break;
			case 60:
				Next_Li(&lex, &(*s), (o7_char)'=', Scanner_LessEqual_cnst, Scanner_Less_cnst);
				break;
			case 62:
				Next_Li(&lex, &(*s), (o7_char)'=', Scanner_GreaterEqual_cnst, Scanner_Greater_cnst);
				break;
			case 38:
				Next_L(&lex, &(*s), Scanner_And_cnst);
				break;
			case 124:
				Next_L(&lex, &(*s), Scanner_Alternative_cnst);
				break;
			case 40:
				Next_L(&lex, &(*s), Scanner_Brace1Open_cnst);
				break;
			case 41:
				Next_L(&lex, &(*s), Scanner_Brace1Close_cnst);
				break;
			case 91:
				Next_L(&lex, &(*s), Scanner_Brace2Open_cnst);
				break;
			case 93:
				Next_L(&lex, &(*s), Scanner_Brace2Close_cnst);
				break;
			case 123:
				Next_L(&lex, &(*s), Scanner_Brace3Open_cnst);
				break;
			case 125:
				Next_L(&lex, &(*s), Scanner_Brace3Close_cnst);
				break;
			case 34:
				lex = ScanString(&(*s));
				break;
			default:
				if ((0 <= o7_case_expr && o7_case_expr <= 3) || (5 <= o7_case_expr && o7_case_expr <= 33) || (o7_case_expr == 36) || (o7_case_expr == 37) || (o7_case_expr == 39) || (o7_case_expr == 63) || (o7_case_expr == 64) || (o7_case_expr == 92) || (o7_case_expr == 95) || (o7_case_expr == 96) || (127 <= o7_case_expr && o7_case_expr <= 255)) {
					lex = Scanner_ErrUnexpectChar_cnst;
					(*s).ind = o7_add((*s).ind, 1);
				} else if ((48 <= o7_case_expr && o7_case_expr <= 57)) {
					lex = SNumber(&(*s));
				} else if ((97 <= o7_case_expr && o7_case_expr <= 122) || (65 <= o7_case_expr && o7_case_expr <= 90)) {
					lex = SWord(&(*s));
				} else o7_case_fail(o7_case_expr);
				break;
			}
		}
		/*
		Log.Str("Scan "); Log.Int(lex); Log.Ln;
		*/
		(*s).lexEnd = o7_int((*s).ind);
		(*s).lexLen = o7_sub(o7_add((*s).lexEnd, o7_mul((int)(o7_cmp((*s).lexEnd, (*s).lexStart) < 0), (O7_LEN((*s).buf) - 1))), (*s).lexStart);
		O7_ASSERT((o7_cmp(0, (*s).lexLen) < 0) || (lex == Scanner_EndOfFile_cnst));
		(*s).column = o7_add((*s).column, (*s).lexLen);
		O7_ASSERT(o7_cmp(0, (*s).column) <= 0);
	}
	return lex;
}

extern o7_bool Scanner_TakeCommentPos(struct Scanner_Scanner *s, int *ofs, int *end) {
	o7_bool ret;

	ret = o7_cmp((*s).commentOfs, 0) >= 0;
	if (ret) {
		(*ofs) = o7_int((*s).commentOfs);
		(*end) = o7_int((*s).commentEnd);
		(*s).commentOfs =  - 1;
	}
	return ret;
}

extern void Scanner_ResetComment(struct Scanner_Scanner *s) {
	(*s).commentOfs =  - 1;
}

extern void Scanner_init(void) {
	static int initialized = 0;
	if (0 == initialized) {
		V_init();
		VDataStream_init();
		Utf8_init();
		TranslatorLimits_init();
		StringStore_init();
		Log_init();


		O7_STATIC_ASSERT(TranslatorLimits_LenName_cnst < Scanner_BlockSize_cnst);
	}
	++initialized;
}

