/* Generated by Vostok - Oberon-07 translator */

/*  Strings storage
 *  Copyright (C) 2016-2017 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_StringStore)
#define HEADER_GUARD_StringStore 1

#include "Log.h"
#include "Utf8.h"
#include "V.h"
#include "VDataStream.h"

#define StringStore_BlockSize_cnst 256

typedef struct StringStore_Block_s {
	V_Base _;
	o7_char s[StringStore_BlockSize_cnst + 1];
	struct StringStore_Block_s *next;
	int num;
} *StringStore_Block;
#define StringStore_Block_s_tag V_Base_tag

extern void StringStore_Block_s_undef(struct StringStore_Block_s *r);

typedef struct StringStore_String {
	V_Base _;
	struct StringStore_Block_s *block;
	int ofs;
} StringStore_String;
#define StringStore_String_tag V_Base_tag

extern void StringStore_String_undef(struct StringStore_String *r);

typedef struct StringStore_Iterator {
	V_Base _;
	o7_char char_;
	struct StringStore_Block_s *b;
	int i;
} StringStore_Iterator;
#define StringStore_Iterator_tag V_Base_tag

extern void StringStore_Iterator_undef(struct StringStore_Iterator *r);

typedef struct StringStore_Store {
	V_Base _;
	struct StringStore_Block_s *first;
	struct StringStore_Block_s *last;
	int ofs;
} StringStore_Store;
#define StringStore_Store_tag V_Base_tag

extern void StringStore_Store_undef(struct StringStore_Store *r);

extern void StringStore_LogLoopStr(int s_len0, o7_char s[/*len0*/], int j, int end);

extern void StringStore_Undef(struct StringStore_String *s);

extern o7_bool StringStore_IsDefined(struct StringStore_String *s);

extern void StringStore_Put(struct StringStore_Store *store, struct StringStore_String *w, int s_len0, o7_char s[/*len0*/], int j, int end);

extern o7_bool StringStore_GetIter(struct StringStore_Iterator *iter, struct StringStore_String *s, int ofs);

extern o7_bool StringStore_IterNext(struct StringStore_Iterator *iter);

extern o7_char StringStore_GetChar(struct StringStore_String *s, int i);

extern o7_bool StringStore_IsEqualToChars(struct StringStore_String *w, int s_len0, o7_char s[/*len0*/], int j, int end);

extern o7_bool StringStore_IsEqualToString(struct StringStore_String *w, int s_len0, o7_char s[/*len0*/]);

extern int StringStore_Compare(struct StringStore_String *w1, struct StringStore_String *w2);

extern o7_bool StringStore_SearchSubString(struct StringStore_String *w, int s_len0, o7_char s[/*len0*/]);

extern o7_bool StringStore_CopyToChars(int d_len0, o7_char d[/*len0*/], int *dofs, struct StringStore_String *w);

extern void StringStore_StoreInit(struct StringStore_Store *s);

extern void StringStore_StoreDone(struct StringStore_Store *s);

extern o7_bool StringStore_CopyChars(int dest_len0, o7_char dest[/*len0*/], int *destOfs, int src_len0, o7_char src[/*len0*/], int srcOfs, int srcEnd);

extern o7_bool StringStore_CopyCharsNull(int dest_len0, o7_char dest[/*len0*/], int *destOfs, int src_len0, o7_char src[/*len0*/]);

extern int StringStore_CalcLen(int str_len0, o7_char str[/*len0*/], int ofs);

extern int StringStore_Write(struct VDataStream_Out *out, o7_tag_t out_tag, struct StringStore_String *str);

extern void StringStore_init(void);
#endif
