/* Generated by Vostok - Oberon-07 translator */

#include <stdbool.h>

#define O7_BOOL_UNDEFINED
#include <o7.h>

#include "StringStore.h"

#define StringStore_Block_s_tag V_Base_tag
extern void StringStore_Block_s_undef(struct StringStore_Block_s *r) {
	V_Base_undef(&r->_);
	memset(&r->s, 0, sizeof(r->s));
	r->next = NULL;
	r->num = O7_INT_UNDEF;
}
#define StringStore_String_tag V_Base_tag
extern void StringStore_String_undef(struct StringStore_String *r) {
	V_Base_undef(&r->_);
	r->block = NULL;
	r->ofs = O7_INT_UNDEF;
}
#define StringStore_Iterator_tag V_Base_tag
extern void StringStore_Iterator_undef(struct StringStore_Iterator *r) {
	V_Base_undef(&r->_);
	r->char_ = '\0';
	r->b = NULL;
	r->i = O7_INT_UNDEF;
}
#define StringStore_Store_tag V_Base_tag
extern void StringStore_Store_undef(struct StringStore_Store *r) {
	V_Base_undef(&r->_);
	r->first = NULL;
	r->last = NULL;
	r->ofs = O7_INT_UNDEF;
}

extern void StringStore_LogLoopStr(int s_len0, o7_char s[/*len0*/], int j, int end) {
	while (o7_cmp(j, end) !=  0) {
		Log_Char(s[o7_ind(s_len0, j)]);
		j = o7_mod((o7_add(j, 1)), (o7_sub(s_len0, 1)));
	}
}

extern void StringStore_Undef(struct StringStore_String *s) {
	V_Init(&(*s)._);
	(*s).block = NULL;
	(*s).ofs =  - 1;
}

extern o7_bool StringStore_IsDefined(struct StringStore_String *s) {
	return (*s).block != NULL;
}

static void Put_AddBlock(struct StringStore_Block_s **b, int *i) {
	O7_ASSERT(O7_REF((*b))->next == NULL);
	(*i) = 0;
	O7_NEW(&O7_REF((*b))->next, StringStore_Block_s);
	V_Init(&(*O7_REF(O7_REF((*b))->next))._);
	O7_REF(O7_REF((*b))->next)->num = o7_add(O7_REF((*b))->num, 1);
	(*b) = O7_REF((*b))->next;
	O7_REF((*b))->next = NULL;
}

extern void StringStore_Put(struct StringStore_Store *store, struct StringStore_String *w, int s_len0, o7_char s[/*len0*/], int j, int end) {
	struct StringStore_Block_s *b = NULL;
	int i = O7_INT_UNDEF;

	O7_ASSERT((s_len0 % 2 == 1) || (o7_cmp(j, end) <=  0));
	O7_ASSERT((o7_cmp(0, j) <=  0) && (o7_cmp(j, o7_sub(s_len0, 1)) <  0));
	O7_ASSERT((o7_cmp(0, end) <=  0) && (o7_cmp(end, o7_sub(s_len0, 1)) <  0));
	b = (*store).last;
	i = o7_int((*store).ofs);
	V_Init(&(*w)._);
	(*w).block = b;
	(*w).ofs = o7_int(i);
	/*Log.Str("Put "); Log.Int(b.num); Log.Str(":"); Log.Int(i); Log.Ln;*/
	while (o7_cmp(j, end) !=  0) {
		if (o7_cmp(i, O7_LEN(O7_REF(b)->s) - 1) ==  0) {
			O7_ASSERT(o7_cmp(i, (*w).ofs) !=  0);
			O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] = 0x0Cu;
			Put_AddBlock(&b, &i);
		}
		O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] = s[o7_ind(s_len0, j)];
		O7_ASSERT(s[o7_ind(s_len0, j)] != 0x0Cu);
		i = o7_add(i, 1);
		j = o7_mod((o7_add(j, 1)), (o7_sub(s_len0, 1)));
	}
	O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] = 0x00u;
	if (o7_cmp(i, O7_LEN(O7_REF(b)->s) - 2) <  0) {
		i = o7_add(i, 1);
	} else {
		Put_AddBlock(&b, &i);
	}
	(*store).last = b;
	(*store).ofs = o7_int(i);
}

extern o7_bool StringStore_GetIter(struct StringStore_Iterator *iter, struct StringStore_String *s, int ofs) {
	O7_ASSERT(o7_cmp(0, ofs) <=  0);
	if ((*s).block != NULL) {
		V_Init(&(*iter)._);
		(*iter).b = (*s).block;
		(*iter).i = o7_int((*s).ofs);
		while (1) if (O7_REF((*iter).b)->s[o7_ind(StringStore_BlockSize_cnst + 1, (*iter).i)] == 0x0Cu) {
			(*iter).b = O7_REF((*iter).b)->next;
			(*iter).i = 0;
		} else if ((o7_cmp(ofs, 0) >  0) && (O7_REF((*iter).b)->s[o7_ind(StringStore_BlockSize_cnst + 1, (*iter).i)] != 0x00u)) {
			ofs = o7_sub(ofs, 1);
			(*iter).i = o7_add((*iter).i, 1);
		} else break;
		(*iter).char_ = O7_REF((*iter).b)->s[o7_ind(StringStore_BlockSize_cnst + 1, (*iter).i)];
	}
	return ((*s).block != NULL) && (O7_REF((*iter).b)->s[o7_ind(StringStore_BlockSize_cnst + 1, (*iter).i)] != 0x00u);
}

extern o7_bool StringStore_IterNext(struct StringStore_Iterator *iter) {
	if ((*iter).char_ != 0x00u) {
		(*iter).i = o7_add((*iter).i, 1);
		if (O7_REF((*iter).b)->s[o7_ind(StringStore_BlockSize_cnst + 1, (*iter).i)] == 0x0Cu) {
			(*iter).b = O7_REF((*iter).b)->next;
			(*iter).i = 0;
		}
		(*iter).char_ = O7_REF((*iter).b)->s[o7_ind(StringStore_BlockSize_cnst + 1, (*iter).i)];
	}
	return (*iter).char_ != 0x00u;
}

extern o7_char StringStore_GetChar(struct StringStore_String *s, int i) {
	int ofs = O7_INT_UNDEF;
	struct StringStore_Block_s *b = NULL;

	O7_ASSERT((o7_cmp(0, i) <=  0) && (o7_cmp(i, StringStore_BlockSize_cnst * StringStore_BlockSize_cnst) <  0));
	ofs = o7_add((*s).ofs, i);
	b = (*s).block;
	while (o7_cmp(StringStore_BlockSize_cnst, ofs) <=  0) {
		b = O7_REF(b)->next;
		ofs = o7_sub(ofs, StringStore_BlockSize_cnst);
	}
	return O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, ofs)];
}

extern o7_bool StringStore_IsEqualToChars(struct StringStore_String *w, int s_len0, o7_char s[/*len0*/], int j, int end) {
	int i = O7_INT_UNDEF;
	struct StringStore_Block_s *b = NULL;

	/*ASSERT(ODD(LEN(s)));*/
	O7_ASSERT((o7_cmp(j, 0) >=  0) && (o7_cmp(j, o7_sub(s_len0, 1)) <  0));
	O7_ASSERT((o7_cmp(0, end) <=  0) && (o7_cmp(end, o7_sub(s_len0, 1)) <  0));
	i = o7_int((*w).ofs);
	b = (*w).block;
	while (1) if ((O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == s[o7_ind(s_len0, j)]) && (o7_cmp(j, end) !=  0)) {
		i = o7_add(i, 1);
		j = o7_mod((o7_add(j, 1)), (o7_sub(s_len0, 1)));
	} else if (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x0Cu) {
		b = O7_REF(b)->next;
		i = 0;
	} else break;
	return (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x00u) && (o7_cmp(j, end) ==  0);
}

extern o7_bool StringStore_IsEqualToString(struct StringStore_String *w, int s_len0, o7_char s[/*len0*/]) {
	int i = O7_INT_UNDEF, j = O7_INT_UNDEF;
	struct StringStore_Block_s *b = NULL;

	j = 0;
	i = o7_int((*w).ofs);
	b = (*w).block;
	while (1) if ((o7_cmp(j, s_len0) <  0) && (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == s[o7_ind(s_len0, j)]) && (s[o7_ind(s_len0, j)] != 0x00u)) {
		/*Log.Char(b.s[i]); Log.Char(s[j]);*/
		i = o7_add(i, 1);
		j = o7_add(j, 1);
	} else if (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x0Cu) {
		b = O7_REF(b)->next;
		i = 0;
	} else break;
	return (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x00u) && ((o7_cmp(j, s_len0) ==  0) || (s[o7_ind(s_len0, j)] == 0x00u));
}

extern int StringStore_Compare(struct StringStore_String *w1, struct StringStore_String *w2) {
	int i1 = O7_INT_UNDEF, i2 = O7_INT_UNDEF, res = O7_INT_UNDEF;
	struct StringStore_Block_s *b1 = NULL, *b2 = NULL;

	i1 = o7_int((*w1).ofs);
	i2 = o7_int((*w2).ofs);
	b1 = (*w1).block;
	b2 = (*w2).block;
	while (1) if (O7_REF(b1)->s[o7_ind(StringStore_BlockSize_cnst + 1, i1)] == 0x0Cu) {
		b1 = O7_REF(b1)->next;
		i1 = 0;
	} else if (O7_REF(b2)->s[o7_ind(StringStore_BlockSize_cnst + 1, i2)] == 0x0Cu) {
		b2 = O7_REF(b2)->next;
		i2 = 0;
	} else if ((O7_REF(b1)->s[o7_ind(StringStore_BlockSize_cnst + 1, i1)] == O7_REF(b2)->s[o7_ind(StringStore_BlockSize_cnst + 1, i2)]) && (O7_REF(b1)->s[o7_ind(StringStore_BlockSize_cnst + 1, i1)] != 0x00u)) {
		i1 = o7_add(i1, 1);
		i2 = o7_add(i2, 1);
	} else break;
	if (O7_REF(b1)->s[o7_ind(StringStore_BlockSize_cnst + 1, i1)] == O7_REF(b2)->s[o7_ind(StringStore_BlockSize_cnst + 1, i2)]) {
		res = 0;
	} else if (O7_REF(b1)->s[o7_ind(StringStore_BlockSize_cnst + 1, i1)] < O7_REF(b2)->s[o7_ind(StringStore_BlockSize_cnst + 1, i2)]) {
		res =  - 1;
	} else {
		res = 1;
	}
	return o7_int(res);
}

extern o7_bool StringStore_SearchSubString(struct StringStore_String *w, int s_len0, o7_char s[/*len0*/]) {
	int i = O7_INT_UNDEF, j = O7_INT_UNDEF;
	struct StringStore_Block_s *b = NULL;

	i = o7_int((*w).ofs);
	b = (*w).block;
	do {
		while (1) if (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x0Cu) {
			b = O7_REF(b)->next;
			i = 0;
		} else if ((O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] != s[0]) && (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] != 0x00u)) {
			i = o7_add(i, 1);
		} else break;
		j = 0;
		while (1) if ((o7_cmp(j, s_len0) <  0) && (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == s[o7_ind(s_len0, j)]) && (s[o7_ind(s_len0, j)] != 0x00u)) {
			i = o7_add(i, 1);
			j = o7_add(j, 1);
		} else if (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x0Cu) {
			b = O7_REF(b)->next;
			i = 0;
		} else break;
	} while (!((o7_cmp(j, s_len0) ==  0) || (s[o7_ind(s_len0, j)] == 0x00u) || (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x00u)));
	return (o7_cmp(j, s_len0) ==  0) || (s[o7_ind(s_len0, j)] == 0x00u);
}

extern o7_bool StringStore_CopyToChars(int d_len0, o7_char d[/*len0*/], int *dofs, struct StringStore_String *w) {
	struct StringStore_Block_s *b = NULL;
	int i = O7_INT_UNDEF;

	b = (*w).block;
	i = o7_int((*w).ofs);
	while (1) if ((o7_cmp((*dofs), o7_sub(d_len0, 1)) <  0) && (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] > 0x0Cu)) {
		d[o7_ind(d_len0, (*dofs))] = O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)];
		(*dofs) = o7_add((*dofs), 1);
		i = o7_add(i, 1);
	} else if (O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] != 0x00u) {
		O7_ASSERT(O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x0Cu);
		b = O7_REF(b)->next;
		i = 0;
	} else break;
	d[o7_ind(d_len0, (*dofs))] = 0x00u;
	return O7_REF(b)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x00u;
}

extern void StringStore_StoreInit(struct StringStore_Store *s) {
	V_Init(&(*s)._);
	O7_NEW(&(*s).first, StringStore_Block_s);
	V_Init(&(*O7_REF((*s).first))._);
	O7_REF((*s).first)->num = 0;
	(*s).last = (*s).first;
	O7_REF((*s).last)->next = NULL;
	(*s).ofs = 0;
}

extern void StringStore_StoreDone(struct StringStore_Store *s) {
	while ((*s).first != NULL) {
		(*s).first = O7_REF((*s).first)->next;
	}
	(*s).last = NULL;
}

extern o7_bool StringStore_CopyChars(int dest_len0, o7_char dest[/*len0*/], int *destOfs, int src_len0, o7_char src[/*len0*/], int srcOfs, int srcEnd) {
	o7_bool ret = O7_BOOL_UNDEF;

	/*
	Log.Str("CopyChars: "); Log.Int(destOfs);
	Log.Str(", "); Log.Int(srcOfs);
	Log.Str(", "); Log.Int(srcEnd);
	Log.Str(" "); Log.StrLn(src);
	*/
	O7_ASSERT((o7_cmp(0, (*destOfs)) <=  0) && (o7_cmp(0, srcOfs) <=  0) && (o7_cmp(srcOfs, srcEnd) <=  0) && (o7_cmp(srcEnd, src_len0) <=  0));

	ret = o7_cmp(o7_sub(o7_add((*destOfs), srcEnd), srcOfs), o7_sub(dest_len0, 1)) <  0;
	if (o7_bl(ret)) {
		while (o7_cmp(srcOfs, srcEnd) <  0) {
			dest[o7_ind(dest_len0, (*destOfs))] = src[o7_ind(src_len0, srcOfs)];
			(*destOfs) = o7_add((*destOfs), 1);
			srcOfs = o7_add(srcOfs, 1);
		}
	}
	dest[o7_ind(dest_len0, (*destOfs))] = 0x00u;
	return o7_bl(ret);
}

/* TODO Не использовать для константных строк, не заканчивающихся 0 */
extern o7_bool StringStore_CopyCharsNull(int dest_len0, o7_char dest[/*len0*/], int *destOfs, int src_len0, o7_char src[/*len0*/]) {
	int i = O7_INT_UNDEF;

	O7_ASSERT(o7_cmp(0, (*destOfs)) <=  0);

	i = 0;
	while ((o7_cmp((*destOfs), o7_sub(dest_len0, 1)) <  0) && (o7_cmp(i, src_len0) <  0) && (src[o7_ind(src_len0, i)] != 0x00u)) {
		dest[o7_ind(dest_len0, (*destOfs))] = src[o7_ind(src_len0, i)];
		(*destOfs) = o7_add((*destOfs), 1);
		i = o7_add(i, 1);
	}
	dest[o7_ind(dest_len0, (*destOfs))] = 0x00u;
	return (o7_cmp(i, src_len0) >=  0) || (src[o7_ind(src_len0, i)] == 0x00u);
}

extern int StringStore_CalcLen(int str_len0, o7_char str[/*len0*/], int ofs) {
	int i = O7_INT_UNDEF;

	i = o7_int(ofs);
	while (str[o7_ind(str_len0, i)] != 0x00u) {
		i = o7_add(i, 1);
	}
	return o7_sub(i, ofs);
}

/*	копирование содержимого строки, не включая завершающего 0 в поток вывода
	TODO учесть возможность ошибки при записи */
extern int StringStore_Write(struct VDataStream_Out *out, o7_tag_t out_tag, struct StringStore_String *str) {
	int i = O7_INT_UNDEF, len = O7_INT_UNDEF, ofs = O7_INT_UNDEF;
	struct StringStore_Block_s *block = NULL;

	block = (*str).block;
	i = o7_int((*str).ofs);
	ofs = o7_int(i);
	len = 0;
	while (1) if (O7_REF(block)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x0Cu) {
		len = o7_add(len, VDataStream_WriteChars(&(*out), out_tag, StringStore_BlockSize_cnst + 1, O7_REF(block)->s, ofs, o7_sub(i, ofs)));
		block = O7_REF(block)->next;
		ofs = 0;
		i = 0;
	} else if (O7_REF(block)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] != 0x00u) {
		i = o7_add(i, 1);
	} else break;
	O7_ASSERT(O7_REF(block)->s[o7_ind(StringStore_BlockSize_cnst + 1, i)] == 0x00u);
	len = VDataStream_WriteChars(&(*out), out_tag, StringStore_BlockSize_cnst + 1, O7_REF(block)->s, ofs, o7_sub(i, ofs));
	return o7_int(len);
}

extern void StringStore_init(void) {
	static int initialized = 0;
	if (0 == initialized) {
		Log_init();
		Utf8_init();
		V_init();
		VDataStream_init();


	}
	++initialized;
}

