/* Generated by Vostok - Oberon-07 translator */

/*  Limits for different parts of the translator
 *  Copyright (C) 2016, 2018 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_TranslatorLimits)
#define HEADER_GUARD_TranslatorLimits 1

#define TranslatorLimits_LenName_cnst 63
#define TranslatorLimits_LenString_cnst 255
#define TranslatorLimits_LenNumber_cnst 63
#define TranslatorLimits_BlankChars_cnst 1023
#define TranslatorLimits_ImportedModules_cnst 127
#define TranslatorLimits_GlobalConsts_cnst 2047
#define TranslatorLimits_GlobalTypes_cnst 127
#define TranslatorLimits_GlobalVars_cnst 255
#define TranslatorLimits_VarsSeparatedByComa_cnst 31
#define TranslatorLimits_GlobalProcedures_cnst 1023
#define TranslatorLimits_ModuleTextSize_cnst 262143
#define TranslatorLimits_ArrayDimension_cnst 7
#define TranslatorLimits_VarsInRecord_cnst 255
#define TranslatorLimits_RecordExt_cnst 15
#define TranslatorLimits_Params_cnst 15
#define TranslatorLimits_Consts_cnst 255
#define TranslatorLimits_Vars_cnst 31
#define TranslatorLimits_Procedures_cnst 31
#define TranslatorLimits_DeepProcedures_cnst 7
#define TranslatorLimits_Statements_cnst 255
#define TranslatorLimits_DeepStatements_cnst 15
#define TranslatorLimits_IfBranches_cnst 255
#define TranslatorLimits_Selectors_cnst 63
#define TranslatorLimits_TermsInSum_cnst 255
#define TranslatorLimits_FactorsInTerm_cnst 255

#endif
