/* Generated by Vostok - Oberon-07 translator */

/*  Oberon-07 types limits
 *  Copyright (C) 2016-2017 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_TypeLimits)
#define HEADER_GUARD_TypeLimits 1


#define TypeLimits_IntegerMax_cnst 2147483647
/* минимальное значение отброшено как усложняющее жизнь и для использования
	   в качестве имитации недопустимого значения */
#define TypeLimits_IntegerMin_cnst (-2147483647)
#define TypeLimits_CharMax_cnst 0xFFu
#define TypeLimits_ByteMax_cnst 255

#define TypeLimits_SetMax_cnst 31
#define TypeLimits_LongSetMax_cnst 63

extern o7_bool TypeLimits_IsNan(double r);

extern o7_bool TypeLimits_InByteRange(int v);

extern o7_bool TypeLimits_InCharRange(int v);

static inline void TypeLimits_init(void) { ; }
#endif
