/* Generated by Vostok - Oberon-07 translator */

#include <stdbool.h>

#define O7_BOOL_UNDEFINED
#include <o7.h>

#include "TypeLimits.h"

extern o7_bool TypeLimits_IsNan(double r) {
	return r != r;
}

extern o7_bool TypeLimits_InByteRange(int v) {
	return (o7_cmp(0, v) <=  0) && (o7_cmp(v, TypeLimits_ByteMax_cnst) <=  0);
}

extern o7_bool TypeLimits_InCharRange(int v) {
	return (o7_cmp(0, v) <=  0) && (o7_cmp(v, (int)0xFFu) <=  0);
}

