/* Generated by Vostok - Oberon-07 translator */

#define O7_BOOL_UNDEFINED
#include <o7.h>

#include "TypeLimits.h"

extern o7_bool TypeLimits_InByteRange(int v) {
	return (0 <= v) && (v <= TypeLimits_ByteMax_cnst);
}

extern o7_bool TypeLimits_InCharRange(int v) {
	return (0 <= v) && (v <= (int)0xFFu);
}
