/* Generated by Vostok - Oberon-07 translator */

/*  Some constants of Utf-8/ASC II
 *  Copyright (C) 2016 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#if !defined(HEADER_GUARD_Utf8)
#define HEADER_GUARD_Utf8 1

#define Utf8_Null_cnst 0x00u
#define Utf8_TransmissionEnd_cnst 0x04u
#define Utf8_Bell_cnst 0x07u
#define Utf8_BackSpace_cnst 0x08u
#define Utf8_Tab_cnst 0x09u
#define Utf8_NewLine_cnst 0x0Au
#define Utf8_NewPage_cnst 0x0Cu
#define Utf8_CarRet_cnst 0x0Du
#define Utf8_Idle_cnst 0x16u
#define Utf8_DQuote_cnst (o7_char)'"'
#define Utf8_Delete_cnst (o7_char)''

#endif
