/* Generated by Vostok - Oberon-07 translator */

/*  Base extensible records for Translator
 *  Copyright (C) 2016 ComdivByZero
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *)
(* база всего сущего, авось пригодится для чего-нибудь эдакого */
#if !defined(HEADER_GUARD_V)
#define HEADER_GUARD_V 1


#define V_ContentPassOpen_cnst 0
#define V_ContentPassNext_cnst 1
#define V_ContentPassClose_cnst 2

typedef struct V_Message { int nothing; } V_Message;
#define V_Message_tag o7_base_tag

extern void V_Message_undef(struct V_Message *r);
typedef struct V_Message *V_PMessage;

typedef o7_bool (*V_Handle)(struct V_Message *this_, struct V_Message *mes);

typedef struct V_Base {
	V_Message _;
	V_Handle do_;
} V_Base;
#define V_Base_tag V_Message_tag

extern void V_Base_undef(struct V_Base *r);
typedef struct V_Base *V_PBase;

typedef struct V_Error {
	V_Base _;
} V_Error;
#define V_Error_tag V_Base_tag

extern void V_Error_undef(struct V_Error *r);
typedef struct V_Error *V_PError;

typedef struct V_MsgFinalize {
	V_Base _;
} V_MsgFinalize;
#define V_MsgFinalize_tag V_Base_tag

extern void V_MsgFinalize_undef(struct V_MsgFinalize *r);
typedef struct V_MsgNeedMemory {
	V_Base _;
} V_MsgNeedMemory;
#define V_MsgNeedMemory_tag V_Base_tag

extern void V_MsgNeedMemory_undef(struct V_MsgNeedMemory *r);
typedef struct V_MsgCopy {
	V_Base _;
	struct V_Base *copy;
} V_MsgCopy;
#define V_MsgCopy_tag V_Base_tag

extern void V_MsgCopy_undef(struct V_MsgCopy *r);
typedef struct V_MsgLinks {
	V_Base _;
	int diff;
	int count;
} V_MsgLinks;
#define V_MsgLinks_tag V_Base_tag

extern void V_MsgLinks_undef(struct V_MsgLinks *r);
typedef struct V_MsgContentPass {
	V_Base _;
	int id;
} V_MsgContentPass;
#define V_MsgContentPass_tag V_Base_tag

extern void V_MsgContentPass_undef(struct V_MsgContentPass *r);
typedef struct V_MsgHash {
	V_Base _;
	int hash;
} V_MsgHash;
#define V_MsgHash_tag V_Base_tag

extern void V_MsgHash_undef(struct V_MsgHash *r);

extern void V_Init(struct V_Base *base);

extern void V_SetDo(struct V_Base *base, V_Handle do_);

extern o7_bool V_Do(struct V_Base *handler, struct V_Message *message);

extern void V_init(void);
#endif
