/* Generated by Vostok - Oberon-07 translator */

/* Copyright 2017 ComdivByZero
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#if !defined HEADER_GUARD_OsEnv
#    define  HEADER_GUARD_OsEnv 1


#define OsEnv_MaxLen_cnst 4096

extern o7_bool OsEnv_Exist(o7_int_t len, o7_char const name[O7_VLA(len)]);

extern o7_bool OsEnv_Get(o7_int_t len, o7_char val[O7_VLA(len)], o7_int_t *ofs,
                         o7_int_t name_len, o7_char const name[O7_VLA(name_len)]);

O7_ALWAYS_INLINE void OsEnv_init(void) { ; }
O7_ALWAYS_INLINE void OsEnv_done(void) { ; }
#endif
