/* Generated by Vostok - Oberon-07 translator */

#if !defined(HEADER_GUARD_PosixDir)
#define HEADER_GUARD_PosixDir 1

typedef struct PosixDir_Dir_s *PosixDir_Dir;
#define PosixDir_Dir_s_tag o7_base_tag
O7_INLINE void PosixDir_Dir_s_undef(PosixDir_Dir r) {}

typedef struct dirent *PosixDir_Ent;
#define PosixDir_Ent_s_tag o7_base_tag
O7_INLINE void PosixDir_Ent_s_undef(PosixDir_Ent r) {}

extern o7_bool PosixDir_Open(PosixDir_Dir *d,
                             int len, o7_char name[O7_VLA(len)], int ofs);

extern o7_bool PosixDir_Close(PosixDir_Dir *d);

extern o7_bool PosixDir_Read(PosixDir_Ent *e, PosixDir_Dir d);

extern o7_bool PosixDir_CopyName(int len, o7_char buf[O7_VLA(len)], int *ofs,
                                 PosixDir_Ent e);

O7_INLINE void PosixDir_init(void) {}
#endif
