/* Generated by Vostok - Oberon-07 translator */

#include <stdbool.h>

#define O7_BOOL_UNDEFINED
#include <o7.h>

#if defined(_WIN16) || defined(_WIN32) || defined(_WIN64)
#	include <io.h>
#else
	struct _finddata_t { char name[1]; };

	O7_INLINE intptr_t findfirst(char const *filespec, struct _finddata_t *fileinfo)
	{ (void)filespec; (void)fileinfo; return -1; }
	O7_INLINE int findnext(intptr_t handle, struct _finddata_t *fileinfo)
	{ (void)handle; (void)fileinfo; return -1; }
	O7_INLINE int findclose(intptr_t handle) { (void)handle; return -1; }
#endif

#include "WindowsDir.h"

struct WindowsDir_FindData_s {
	struct _finddata_t d;
};
extern void WindowsDir_FindData_s_undef(WindowsDir_FindData r) {
	memset(&r->d, 0, sizeof(r->d));
}

struct WindowsDir_FindId_s {
	intptr_t h;
};
extern void WindowsDir_FindId_s_undef(WindowsDir_FindId r) {
	r->h = -1;
}

extern o7_bool WindowsDir_FindFirst(WindowsDir_FindId *id, WindowsDir_FindData *d,
                                    int len, o7_char filespec[O7_VLA(len)], int ofs)
{
	o7_cbool ret;
	assert((0 < ofs) && (ofs < len - 1));
	if (O7_NEW(id, WindowsDir_FindId_s) && O7_NEW(d, WindowsDir_FindData_s)) {
		(*id)->h = findfirst(filespec + ofs, &(*d)->d);
	}
	if ((NULL == *id) || (NULL == *d) || (-1 == (*id)->h)) {
		free(*id); *id = NULL;
		free(*d); *d = NULL;
	}
	return (*id != NULL);
}

extern o7_bool WindowsDir_FindNext(WindowsDir_FindData *d, WindowsDir_FindId id)
{
	assert(id != NULL);

	if (O7_NEW(d, WindowsDir_FindData_s)
	 && (0 != findnext(id->h, &(*d)->d)))
	{
		O7_NULL(d);
	}
	return *d != NULL;
}

extern o7_bool WindowsDir_Close(WindowsDir_FindId *id)
{
	o7_cbool ret;
	ret = (*id == NULL);
	if (!ret) {
		ret = (0 == findclose((*id)->h));
		O7_NULL(id);
	}
	return ret;
}

extern o7_bool WindowsDir_CopyName(int len, o7_char buf[O7_VLA(len)], int *ofs,
                                   WindowsDir_FindData f)
{
	int i, j;
	assert(f != NULL);
	assert((0 <= *ofs) && (*ofs < len));
	i = 0;
	j = *ofs;
	while ((f->d.name[i] != '\0') && (j < len - 1)) {
		buf[j] = f->d.name[i];
		i += 1;
		j += 1;
	}
	buf[j] = '\0';
	*ofs = j;
	return f->d.name[i] == '\0';
}
