name: vostok
base: bare
build-base: core22
adopt-info: ost
license: LGPL-3.0-only
icon: snap/gui/icon.svg
summary: Compiler from Oberon-07 to C/Java/Js/Oberon
description: |
  Translator of Oberon-07 code into readable or error-resistant
  code for a range of industrial programming languages, as well as machine code and
  intermediate representations.
  Package also provide interactive web-environment for the translator.

grade: devel
confinement: classic

architectures:
  - build-on: [amd64]
  - build-on: [amd64]
    build-for: [riscv64]
  - build-on: [i386]
  - build-on: [arm64]
  - build-on: [armhf]
  - build-on: [s390x]
  - build-on: [ppc64el]

parts:
  ost:
    plugin: nil
    build-packages:
      - on amd64 to riscv64:
        - gcc-riscv64-linux-gnu
        - libc6-dev-riscv64-cross
      - else:
        - musl-tools

    override-build: |
      OST=result/ost-run
      if [ "${SNAPCRAFT_TARGET_ARCH}" = riscv64 ]; then
        CC=riscv64-linux-gnu-gcc
        TEST=""
      else
        CC=musl-gcc
        TEST="make.Self; "
      fi
      ./init.sh && result/bs-ost run make.Build -infr . -m source
      mv result/ost $OST
      craftctl set version=$($OST version | awk '{print $2}')
      $OST to-bin Translator.Go result/ost -infr . -m source -cc "$CC -Os -flto -s -static"
      rm -rf $SNAPCRAFT_PART_INSTALL/usr
      mkdir --parents $SNAPCRAFT_PART_INSTALL/usr/{bin,share}
      $OST run 'make.Together(0=0); '"$TEST"'make.InstallTo("'$SNAPCRAFT_PART_INSTALL'/usr")' -infr . -m source
      mkdir --parents $SNAPCRAFT_PART_INSTALL/usr/share/vostok/result
      cp result/ost $SNAPCRAFT_PART_INSTALL/usr/share/vostok/result/

    source:
      .

  web:
    plugin: nil
    build-snaps:
      - go
    build-attributes:
      - no-patchelf
    override-build: |
      if [ "${SNAPCRAFT_TARGET_ARCH}" = riscv64 ]; then
        GOARCH=riscv64 go build -ldflags='-s -w' server.go
      else
        go build -ldflags='-s -w -linkmode external -extldflags "-static"' server.go
      fi
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server
      cp server $SNAPCRAFT_PROJECT_DIR/snap/local/server.sh $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp -r vostok vostok-full web $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server/

    source:
      demo-server


apps:
  vostok:
    command: usr/bin/ost
  web:
    command: usr/bin/server.sh 8080 -share
  local:
    command: usr/bin/server.sh 18083 -local -FULL-ACCESS
