name: vostok
base: core20
adopt-info: ost
license: LGPL-3.0-only
icon: snap/gui/icon.svg
summary: Compiler from Oberon-07 to C/Java/Js/Oberon
description: |
  Translator of Oberon-07 code into readable or error-resistant
  code for a range of industrial programming languages, as well as machine code and
  intermediate representations.
  Package also provide interactive web-environment for the translator.

grade: devel
confinement: classic

parts:
  ost:
    plugin: nil
    override-build: |
      ./init.sh
      result/bs-ost run make.Build -infr . -m source
      result/ost to-bin Translator.Go result/ost -infr . -m source -cc "cc -O1 -flto -s"
      snapcraftctl set-version `result/ost version | awk '{print $2}'`
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share
      result/ost run 'make.Self; make.InstallTo("'$SNAPCRAFT_PART_INSTALL'/usr")' -infr . -m source

    source:
      .

  web:
    plugin: nil
    build-packages:
      - golang-go
    override-build: |
      go build server.go
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server
      cp server $SNAPCRAFT_PROJECT_DIR/snap/local/server.sh $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp -r vostok vostok-full web $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server/
      cd $SNAPCRAFT_PART_INSTALL/usr/share/vostok
      mkdir result
      cd result
      ln -s ../../../bin/ost ./

    source:
      demo-server


apps:
  vostok:
    command: usr/bin/ost
  web:
    command: usr/bin/server.sh 8080 -share
  local:
    command: usr/bin/server.sh 18083 -local -FULL-ACCESS
