name: vostok
base: core18
adopt-info: ost
license: LGPL-3.0-only
icon: snap/gui/icon.svg
summary: Compiler from Oberon-07 to C/Java/Js/Oberon
description: |
  Translator of Oberon-07 code into readable or error-resistant
  code for a range of industrial programming languages, as well as machine code and
  intermediate representations.

grade: devel
confinement: classic

parts:
  ost:
    plugin: nil
    override-build: |
      ./init.sh
      result/bs-ost run make.Build -infr . -m source
      result/ost to-bin Translator.Go result/ost -infr . -m source -cc "cc -O1 -flto -s"
      snapcraftctl set-version `result/ost version | awk '{print $2}'`
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share
      result/ost run 'make.Self; make.InstallTo("'$SNAPCRAFT_PART_INSTALL'/usr")' -infr . -m source

    source:
      .

apps:
  vostok:
    command: usr/bin/ost
