name: vostok
base: core18
adopt-info: ost
license: LGPL-3.0-only
icon: snap/gui/icon.svg
summary: Compiler from Oberon-07 to C/Java/Js/Oberon
description: |
  Translator of Oberon-07 code into readable or error-resistant
  code for a range of industrial programming languages, as well as machine code and
  intermediate representations.
  Package also provide interactive web-environment for the translator.

grade: devel
confinement: classic

parts:
  ost:
    plugin: nil
    override-build: |
      ./init.sh
      result/bs-ost run make.Build -infr . -m source
      if [ "${SNAPCRAFT_TARGET_ARCH}" = "riscv64" ]; then
        CC=riscv64-linux-gnu-gcc
        OSTRUN=result/ost-run
        mv result/ost $OSTRUN
      else
        CC=gcc
        OSTRUN=result/ost
      fi
      $OSTRUN to-bin Translator.Go result/ost -infr . -m source -cc "$CC -Os -flto -s"
      snapcraftctl set-version `$OSTRUN version | awk '{print $2}'`
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share
      if [ "$CC" = "gcc" ]; then
        $OSTRUN run 'make.Self; make.InstallTo("'$SNAPCRAFT_PART_INSTALL'/usr")' -infr . -m source
      else
        $OSTRUN run 'make.InstallTo("'$SNAPCRAFT_PART_INSTALL'/usr")' -infr . -m source
      fi
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/vostok/result
      cp result/ost $SNAPCRAFT_PART_INSTALL/usr/share/vostok/result/

    source:
      .

  web:
    plugin: nil
    build-snaps:
      - go
    build-attributes:
      - no-patchelf
    override-build: |
      if [ "${SNAPCRAFT_TARGET_ARCH}" = "riscv64" ]; then
        GOARCH=riscv64 go build -ldflags='-s -w' server.go
      else
        go build -ldflags='-s -w' server.go
      fi
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server
      cp server $SNAPCRAFT_PROJECT_DIR/snap/local/server.sh $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp -r vostok vostok-full web $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server/

    source:
      demo-server


apps:
  vostok:
    command: usr/bin/ost
  web:
    command: usr/bin/server.sh 8080 -share
  local:
    command: usr/bin/server.sh 18083 -local -FULL-ACCESS
