name: vostok
base: bare
build-base: core22
adopt-info: ost
license: LGPL-3.0-only
icon: snap/gui/icon.svg
summary: Compiler from Oberon-07 to C/Java/Js/Oberon
description: |
  Translator of Oberon-07 code into readable or error-resistant
  code for a range of industrial programming languages, as well as machine code and
  intermediate representations.
  Package also provide interactive web-environment for the translator.

grade: devel
confinement: classic

#architectures: --build-for=amd64,arm64,armhf,riscv64,s390x,ppc64el

parts:
  ost:
    plugin: nil
    build-packages:
      - musl-tools

    override-build: |
      OST=result/ost-run
      SPLITEST() { $OST run 'make.Together(0=1); make.Test' -infr . -m source && false; }
      if [ "${SNAPCRAFT_TARGET_ARCH}" = armhf ]; then
        CC="musl-gcc -O1 -flto=auto -s -static"
      else
        CC="musl-gcc -Os -flto=auto -s -static"
      fi
      TEST="make.Self;"
      ./init.sh && result/bs-ost run make.Build -infr . -m source
      mv result/ost $OST
      VERSION=$($OST version | awk '{print $2}')
      craftctl set version=$VERSION || snapcraftctl set-version $VERSION
      $OST to-bin Translator.Go result/ost -infr . -m source -cc "$CC"
      rm -rf $SNAPCRAFT_PART_INSTALL/usr
      mkdir --parents $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share
      $OST run "$TEST"'make.InstallTo("'$SNAPCRAFT_PART_INSTALL'/usr")' -infr . -m source || SPLITEST
      mkdir --parents $SNAPCRAFT_PART_INSTALL/usr/share/vostok/result
      cp result/ost $SNAPCRAFT_PART_INSTALL/usr/share/vostok/result/

    source:
      .

  web:
    plugin: nil
    build-snaps:
      - go
    build-attributes:
      - no-patchelf
    override-build: |
      go build -ldflags='-s -w -linkmode external -extldflags "-static"' server.go
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server
      cp server $SNAPCRAFT_PROJECT_DIR/snap/local/server.sh $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s .. vostok-full
      cp -r vostok vostok-full web $SNAPCRAFT_PART_INSTALL/usr/share/vostok/server/

    source:
      demo-server


apps:
  vostok:
    command: usr/bin/ost
  web:
    command: usr/bin/server.sh 8080 -share
  local:
    command: usr/bin/server.sh 18083 -local -FULL-ACCESS
