/* Generated by Vostok - Oberon-07 translator */

/* Copyright 2017 ComdivByZero
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <stdbool.h>
#include <assert.h>
#include <stdlib.h>

#define O7_BOOL_UNDEFINED
#include <o7c.h>

#include "OsEnv.h"

extern o7c_bool OsEnv_Exist(int len, o7c_char const name[O7C_VLA_LEN(len)]) {
	return NULL != getenv((char *)name);
}

extern o7c_bool OsEnv_Get(int len, o7c_char val[O7C_VLA_LEN(len)], int *ofs,
                         int name_len, o7c_char const name[O7C_VLA_LEN(name_len)])
{
	char *env;
	int i, j;
	assert((0 <= *ofs) && (*ofs < len - 1));

	env = getenv((char *)name);
	if (NULL != env) {
		i = *ofs;
		j = 0;
		while ((i < len - 1) && (env[j] != '\0')) {
			val[i] = (o7c_char)env[j];
			i += 1;
			j += 1;
		}
		val[i] = '\0';
		*ofs = i;
	}
	return (NULL != env) && ('\0' == env[j]);
}

